package model.services.client;

import model.services.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 25 16:26:52 BDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }


    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSessionValues",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {orgId, userId, respId, respAppl});
        return;
    }

    public String getAttachments() {
        Object _ret = this.riInvokeExportedMethod(this,"getAttachments",null,null);
        return (String)_ret;
    }

    public void SelectAllRequisitions(String flag) {
        Object _ret =
            this.riInvokeExportedMethod(this,"SelectAllRequisitions",new String [] {"java.lang.String"},new Object[] {flag});
        return;
    }
}
