package model.entity;

import java.sql.SQLException;

import java.util.Map;

import model.services.AppModuleImpl;

import oracle.adf.model.BindingContext;
import oracle.adf.model.binding.DCBindingContainer;
import oracle.adf.model.binding.DCDataControl;
import oracle.adf.share.ADFContext;

import oracle.jbo.ApplicationModule;
import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jul 08 11:24:16 BDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjOntSampleStatusEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        HeaderId {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getHeaderId();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        BuyerId {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getBuyerId();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        Season {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getSeason();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        Brand {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getBrand();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setBrand((String)value);
            }
        }
        ,
        StyleName {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getStyleName();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setStyleName((String)value);
            }
        }
        ,
        StyleNo {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getStyleNo();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setStyleNo((String)value);
            }
        }
        ,
        SampleType {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getSampleType();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setSampleType((String)value);
            }
        }
        ,
        Color {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getColor();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setColor((String)value);
            }
        }
        ,
        UserGroup {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getUserGroup();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setUserGroup((String)value);
            }
        }
        ,
        Item {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getItem();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setItem((String)value);
            }
        }
        ,
        MListNumber {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getMListNumber();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setMListNumber((String)value);
            }
        }
        ,
        MerchandiserId {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getMerchandiserId();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setMerchandiserId((Number)value);
            }
        }
        ,
        RequestDate {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getRequestDate();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setRequestDate((Date)value);
            }
        }
        ,
        NumberOfGarments {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getNumberOfGarments();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setNumberOfGarments((String)value);
            }
        }
        ,
        QuotationRcvdDate {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getQuotationRcvdDate();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setQuotationRcvdDate((Date)value);
            }
        }
        ,
        SampleRequestRcvdDate {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getSampleRequestRcvdDate();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setSampleRequestRcvdDate((Date)value);
            }
        }
        ,
        MlistRcvdDate {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getMlistRcvdDate();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setMlistRcvdDate((Date)value);
            }
        }
        ,
        WashStandardRcvdDate {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getWashStandardRcvdDate();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setWashStandardRcvdDate((Date)value);
            }
        }
        ,
        OtherInfoRcvdDate {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getOtherInfoRcvdDate();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setOtherInfoRcvdDate((Date)value);
            }
        }
        ,
        DropDate {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getDropDate();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setDropDate((Date)value);
            }
        }
        ,
        SampleSubmissionDate {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getSampleSubmissionDate();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setSampleSubmissionDate((Date)value);
            }
        }
        ,
        OrgId {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getOrgId();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        SampleDocNo {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getSampleDocNo();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setSampleDocNo((Number)value);
            }
        }
        ,
        DropPeriod {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getDropPeriod();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setDropPeriod((String)value);
            }
        }
        ,
        Fit {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getFit();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setFit((String)value);
            }
        }
        ,
        DevelopmentPakRecDate {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getDevelopmentPakRecDate();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setDevelopmentPakRecDate((Date)value);
            }
        }
        ,
        MerchandiserName {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getMerchandiserName();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setMerchandiserName((String)value);
            }
        }
        ,
        SampleReceivedDate {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getSampleReceivedDate();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setSampleReceivedDate((Date)value);
            }
        }
        ,
        OtherInfoDetail {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getOtherInfoDetail();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setOtherInfoDetail((String)value);
            }
        }
        ,
        OrderProjectionNo {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getOrderProjectionNo();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setOrderProjectionNo((Number)value);
            }
        }
        ,
        ProStyleNo {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getProStyleNo();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setProStyleNo((String)value);
            }
        }
        ,
        BuyerMerchandiser {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getBuyerMerchandiser();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setBuyerMerchandiser((String)value);
            }
        }
        ,
        ItemDesc {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getItemDesc();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setItemDesc((String)value);
            }
        }
        ,
        VersionNo {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getVersionNo();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setVersionNo((Number)value);
            }
        }
        ,
        VersionDate {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getVersionDate();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setVersionDate((Date)value);
            }
        }
        ,
        Cal {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getCal();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setCal((String)value);
            }
        }
        ,
        Cgl {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getCgl();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setCgl((String)value);
            }
        }
        ,
        Gdl {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getGdl();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setGdl((String)value);
            }
        }
        ,
        Gfl {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getGfl();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setGfl((String)value);
            }
        }
        ,
        Plan {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getPlan();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setPlan((String)value);
            }
        }
        ,
        RespId {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getRespId();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setRespId((Number)value);
            }
        }
        ,
        SendNotificationTo {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getSendNotificationTo();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setSendNotificationTo((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        SampleStatus {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getSampleStatus();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setSampleStatus((String)value);
            }
        }
        ,
        SubmitStatusMessage {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getSubmitStatusMessage();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setSubmitStatusMessage((String)value);
            }
        }
        ,
        Status {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getStatus();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setStatus((Number)value);
            }
        }
        ,
        ExcelFormatChoice {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getExcelFormatChoice();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setExcelFormatChoice((String)value);
            }
        }
        ,
        WashingUnit {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getWashingUnit();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setWashingUnit((String)value);
            }
        }
        ,
        RespIdSampleSection {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getRespIdSampleSection();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setRespIdSampleSection((String)value);
            }
        }
        ,
        SampleComment {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getSampleComment();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setSampleComment((String)value);
            }
        }
        ,
        Comments {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getComments();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setComments((String)value);
            }
        }
        ,
        MnjOntSampleStatusLineEO {
            public Object get(MnjOntSampleStatusEOImpl obj) {
                return obj.getMnjOntSampleStatusLineEO();
            }

            public void put(MnjOntSampleStatusEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjOntSampleStatusEOImpl object);

        public abstract void put(MnjOntSampleStatusEOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int BRAND = AttributesEnum.Brand.index();
    public static final int STYLENAME = AttributesEnum.StyleName.index();
    public static final int STYLENO = AttributesEnum.StyleNo.index();
    public static final int SAMPLETYPE = AttributesEnum.SampleType.index();
    public static final int COLOR = AttributesEnum.Color.index();
    public static final int USERGROUP = AttributesEnum.UserGroup.index();
    public static final int ITEM = AttributesEnum.Item.index();
    public static final int MLISTNUMBER = AttributesEnum.MListNumber.index();
    public static final int MERCHANDISERID = AttributesEnum.MerchandiserId.index();
    public static final int REQUESTDATE = AttributesEnum.RequestDate.index();
    public static final int NUMBEROFGARMENTS = AttributesEnum.NumberOfGarments.index();
    public static final int QUOTATIONRCVDDATE = AttributesEnum.QuotationRcvdDate.index();
    public static final int SAMPLEREQUESTRCVDDATE = AttributesEnum.SampleRequestRcvdDate.index();
    public static final int MLISTRCVDDATE = AttributesEnum.MlistRcvdDate.index();
    public static final int WASHSTANDARDRCVDDATE = AttributesEnum.WashStandardRcvdDate.index();
    public static final int OTHERINFORCVDDATE = AttributesEnum.OtherInfoRcvdDate.index();
    public static final int DROPDATE = AttributesEnum.DropDate.index();
    public static final int SAMPLESUBMISSIONDATE = AttributesEnum.SampleSubmissionDate.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int SAMPLEDOCNO = AttributesEnum.SampleDocNo.index();
    public static final int DROPPERIOD = AttributesEnum.DropPeriod.index();
    public static final int FIT = AttributesEnum.Fit.index();
    public static final int DEVELOPMENTPAKRECDATE = AttributesEnum.DevelopmentPakRecDate.index();
    public static final int MERCHANDISERNAME = AttributesEnum.MerchandiserName.index();
    public static final int SAMPLERECEIVEDDATE = AttributesEnum.SampleReceivedDate.index();
    public static final int OTHERINFODETAIL = AttributesEnum.OtherInfoDetail.index();
    public static final int ORDERPROJECTIONNO = AttributesEnum.OrderProjectionNo.index();
    public static final int PROSTYLENO = AttributesEnum.ProStyleNo.index();
    public static final int BUYERMERCHANDISER = AttributesEnum.BuyerMerchandiser.index();
    public static final int ITEMDESC = AttributesEnum.ItemDesc.index();
    public static final int VERSIONNO = AttributesEnum.VersionNo.index();
    public static final int VERSIONDATE = AttributesEnum.VersionDate.index();
    public static final int CAL = AttributesEnum.Cal.index();
    public static final int CGL = AttributesEnum.Cgl.index();
    public static final int GDL = AttributesEnum.Gdl.index();
    public static final int GFL = AttributesEnum.Gfl.index();
    public static final int PLAN = AttributesEnum.Plan.index();
    public static final int RESPID = AttributesEnum.RespId.index();
    public static final int SENDNOTIFICATIONTO = AttributesEnum.SendNotificationTo.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int SAMPLESTATUS = AttributesEnum.SampleStatus.index();
    public static final int SUBMITSTATUSMESSAGE = AttributesEnum.SubmitStatusMessage.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int EXCELFORMATCHOICE = AttributesEnum.ExcelFormatChoice.index();
    public static final int WASHINGUNIT = AttributesEnum.WashingUnit.index();
    public static final int RESPIDSAMPLESECTION = AttributesEnum.RespIdSampleSection.index();
    public static final int SAMPLECOMMENT = AttributesEnum.SampleComment.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int MNJONTSAMPLESTATUSLINEEO = AttributesEnum.MnjOntSampleStatusLineEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjOntSampleStatusEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.entity.MnjOntSampleStatusEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for BuyerId, using the alias name BuyerId.
     * @return the BuyerId
     */
    public Number getBuyerId() {
        return (Number)getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuyerId.
     * @param value value to set the BuyerId
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for Season, using the alias name Season.
     * @return the Season
     */
    public String getSeason() {
        return (String)getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for Season.
     * @param value value to set the Season
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for Brand, using the alias name Brand.
     * @return the Brand
     */
    public String getBrand() {
        return (String)getAttributeInternal(BRAND);
    }

    /**
     * Sets <code>value</code> as the attribute value for Brand.
     * @param value value to set the Brand
     */
    public void setBrand(String value) {
        setAttributeInternal(BRAND, value);
    }

    /**
     * Gets the attribute value for StyleName, using the alias name StyleName.
     * @return the StyleName
     */
    public String getStyleName() {
        return (String)getAttributeInternal(STYLENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for StyleName.
     * @param value value to set the StyleName
     */
    public void setStyleName(String value) {
        setAttributeInternal(STYLENAME, value);
    }

    /**
     * Gets the attribute value for StyleNo, using the alias name StyleNo.
     * @return the StyleNo
     */
    public String getStyleNo() {
        return (String)getAttributeInternal(STYLENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for StyleNo.
     * @param value value to set the StyleNo
     */
    public void setStyleNo(String value) {
        setAttributeInternal(STYLENO, value);
    }

    /**
     * Gets the attribute value for SampleType, using the alias name SampleType.
     * @return the SampleType
     */
    public String getSampleType() {
        return (String)getAttributeInternal(SAMPLETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SampleType.
     * @param value value to set the SampleType
     */
    public void setSampleType(String value) {
        setAttributeInternal(SAMPLETYPE, value);
    }

    /**
     * Gets the attribute value for Color, using the alias name Color.
     * @return the Color
     */
    public String getColor() {
        return (String)getAttributeInternal(COLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Color.
     * @param value value to set the Color
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**
     * Gets the attribute value for UserGroup, using the alias name UserGroup.
     * @return the UserGroup
     */
    public String getUserGroup() {
        return (String)getAttributeInternal(USERGROUP);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserGroup.
     * @param value value to set the UserGroup
     */
    public void setUserGroup(String value) {
        setAttributeInternal(USERGROUP, value);
    }

    /**
     * Gets the attribute value for Item, using the alias name Item.
     * @return the Item
     */
    public String getItem() {
        return (String)getAttributeInternal(ITEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Item.
     * @param value value to set the Item
     */
    public void setItem(String value) {
        setAttributeInternal(ITEM, value);
    }

    /**
     * Gets the attribute value for MListNumber, using the alias name MListNumber.
     * @return the MListNumber
     */
    public String getMListNumber() {
        return (String)getAttributeInternal(MLISTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for MListNumber.
     * @param value value to set the MListNumber
     */
    public void setMListNumber(String value) {
        setAttributeInternal(MLISTNUMBER, value);
    }

    /**
     * Gets the attribute value for MerchandiserId, using the alias name MerchandiserId.
     * @return the MerchandiserId
     */
    public Number getMerchandiserId() {
        return (Number)getAttributeInternal(MERCHANDISERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MerchandiserId.
     * @param value value to set the MerchandiserId
     */
    public void setMerchandiserId(Number value) {
        setAttributeInternal(MERCHANDISERID, value);
    }

    /**
     * Gets the attribute value for RequestDate, using the alias name RequestDate.
     * @return the RequestDate
     */
    public Date getRequestDate() {
        return (Date)getAttributeInternal(REQUESTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequestDate.
     * @param value value to set the RequestDate
     */
    public void setRequestDate(Date value) {
        setAttributeInternal(REQUESTDATE, value);
    }

    /**
     * Gets the attribute value for NumberOfGarments, using the alias name NumberOfGarments.
     * @return the NumberOfGarments
     */
    public String getNumberOfGarments() {
        return (String)getAttributeInternal(NUMBEROFGARMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for NumberOfGarments.
     * @param value value to set the NumberOfGarments
     */
    public void setNumberOfGarments(String value) {
        setAttributeInternal(NUMBEROFGARMENTS, value);
    }

    /**
     * Gets the attribute value for QuotationRcvdDate, using the alias name QuotationRcvdDate.
     * @return the QuotationRcvdDate
     */
    public Date getQuotationRcvdDate() {
        return (Date)getAttributeInternal(QUOTATIONRCVDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for QuotationRcvdDate.
     * @param value value to set the QuotationRcvdDate
     */
    public void setQuotationRcvdDate(Date value) {
        setAttributeInternal(QUOTATIONRCVDDATE, value);
    }

    /**
     * Gets the attribute value for SampleRequestRcvdDate, using the alias name SampleRequestRcvdDate.
     * @return the SampleRequestRcvdDate
     */
    public Date getSampleRequestRcvdDate() {
        return (Date)getAttributeInternal(SAMPLEREQUESTRCVDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SampleRequestRcvdDate.
     * @param value value to set the SampleRequestRcvdDate
     */
    public void setSampleRequestRcvdDate(Date value) {
        setAttributeInternal(SAMPLEREQUESTRCVDDATE, value);
    }

    /**
     * Gets the attribute value for MlistRcvdDate, using the alias name MlistRcvdDate.
     * @return the MlistRcvdDate
     */
    public Date getMlistRcvdDate() {
        return (Date)getAttributeInternal(MLISTRCVDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for MlistRcvdDate.
     * @param value value to set the MlistRcvdDate
     */
    public void setMlistRcvdDate(Date value) {
        setAttributeInternal(MLISTRCVDDATE, value);
    }

    /**
     * Gets the attribute value for WashStandardRcvdDate, using the alias name WashStandardRcvdDate.
     * @return the WashStandardRcvdDate
     */
    public Date getWashStandardRcvdDate() {
        return (Date)getAttributeInternal(WASHSTANDARDRCVDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashStandardRcvdDate.
     * @param value value to set the WashStandardRcvdDate
     */
    public void setWashStandardRcvdDate(Date value) {
        setAttributeInternal(WASHSTANDARDRCVDDATE, value);
    }

    /**
     * Gets the attribute value for OtherInfoRcvdDate, using the alias name OtherInfoRcvdDate.
     * @return the OtherInfoRcvdDate
     */
    public Date getOtherInfoRcvdDate() {
        return (Date)getAttributeInternal(OTHERINFORCVDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OtherInfoRcvdDate.
     * @param value value to set the OtherInfoRcvdDate
     */
    public void setOtherInfoRcvdDate(Date value) {
        setAttributeInternal(OTHERINFORCVDDATE, value);
    }

    /**
     * Gets the attribute value for DropDate, using the alias name DropDate.
     * @return the DropDate
     */
    public Date getDropDate() {
        return (Date)getAttributeInternal(DROPDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DropDate.
     * @param value value to set the DropDate
     */
    public void setDropDate(Date value) {
        setAttributeInternal(DROPDATE, value);
    }

    /**
     * Gets the attribute value for SampleSubmissionDate, using the alias name SampleSubmissionDate.
     * @return the SampleSubmissionDate
     */
    public Date getSampleSubmissionDate() {
        return (Date)getAttributeInternal(SAMPLESUBMISSIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SampleSubmissionDate.
     * @param value value to set the SampleSubmissionDate
     */
    public void setSampleSubmissionDate(Date value) {
        setAttributeInternal(SAMPLESUBMISSIONDATE, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for SampleDocNo, using the alias name SampleDocNo.
     * @return the SampleDocNo
     */
    public Number getSampleDocNo() {
        return (Number)getAttributeInternal(SAMPLEDOCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SampleDocNo.
     * @param value value to set the SampleDocNo
     */
    public void setSampleDocNo(Number value) {
        setAttributeInternal(SAMPLEDOCNO, value);
    }

    /**
     * Gets the attribute value for DropPeriod, using the alias name DropPeriod.
     * @return the DropPeriod
     */
    public String getDropPeriod() {
        return (String)getAttributeInternal(DROPPERIOD);
    }

    /**
     * Sets <code>value</code> as the attribute value for DropPeriod.
     * @param value value to set the DropPeriod
     */
    public void setDropPeriod(String value) {
        setAttributeInternal(DROPPERIOD, value);
    }

    /**
     * Gets the attribute value for Fit, using the alias name Fit.
     * @return the Fit
     */
    public String getFit() {
        return (String)getAttributeInternal(FIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Fit.
     * @param value value to set the Fit
     */
    public void setFit(String value) {
        setAttributeInternal(FIT, value);
    }

    /**
     * Gets the attribute value for DevelopmentPakRecDate, using the alias name DevelopmentPakRecDate.
     * @return the DevelopmentPakRecDate
     */
    public Date getDevelopmentPakRecDate() {
        return (Date)getAttributeInternal(DEVELOPMENTPAKRECDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DevelopmentPakRecDate.
     * @param value value to set the DevelopmentPakRecDate
     */
    public void setDevelopmentPakRecDate(Date value) {
        setAttributeInternal(DEVELOPMENTPAKRECDATE, value);
    }

    /**
     * Gets the attribute value for MerchandiserName, using the alias name MerchandiserName.
     * @return the MerchandiserName
     */
    public String getMerchandiserName() {
        return (String)getAttributeInternal(MERCHANDISERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for MerchandiserName.
     * @param value value to set the MerchandiserName
     */
    public void setMerchandiserName(String value) {
        setAttributeInternal(MERCHANDISERNAME, value);
    }

    /**
     * Gets the attribute value for SampleReceivedDate, using the alias name SampleReceivedDate.
     * @return the SampleReceivedDate
     */
    public Date getSampleReceivedDate() {
        return (Date)getAttributeInternal(SAMPLERECEIVEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SampleReceivedDate.
     * @param value value to set the SampleReceivedDate
     */
    public void setSampleReceivedDate(Date value) {
        setAttributeInternal(SAMPLERECEIVEDDATE, value);
    }

    /**
     * Gets the attribute value for OtherInfoDetail, using the alias name OtherInfoDetail.
     * @return the OtherInfoDetail
     */
    public String getOtherInfoDetail() {
        return (String)getAttributeInternal(OTHERINFODETAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for OtherInfoDetail.
     * @param value value to set the OtherInfoDetail
     */
    public void setOtherInfoDetail(String value) {
        setAttributeInternal(OTHERINFODETAIL, value);
    }

    /**
     * Gets the attribute value for OrderProjectionNo, using the alias name OrderProjectionNo.
     * @return the OrderProjectionNo
     */
    public Number getOrderProjectionNo() {
        return (Number)getAttributeInternal(ORDERPROJECTIONNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderProjectionNo.
     * @param value value to set the OrderProjectionNo
     */
    public void setOrderProjectionNo(Number value) {
        setAttributeInternal(ORDERPROJECTIONNO, value);
    }

    /**
     * Gets the attribute value for ProStyleNo, using the alias name ProStyleNo.
     * @return the ProStyleNo
     */
    public String getProStyleNo() {
        return (String)getAttributeInternal(PROSTYLENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProStyleNo.
     * @param value value to set the ProStyleNo
     */
    public void setProStyleNo(String value) {
        setAttributeInternal(PROSTYLENO, value);
    }

    /**
     * Gets the attribute value for BuyerMerchandiser, using the alias name BuyerMerchandiser.
     * @return the BuyerMerchandiser
     */
    public String getBuyerMerchandiser() {
        return (String)getAttributeInternal(BUYERMERCHANDISER);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuyerMerchandiser.
     * @param value value to set the BuyerMerchandiser
     */
    public void setBuyerMerchandiser(String value) {
        setAttributeInternal(BUYERMERCHANDISER, value);
    }

    /**
     * Gets the attribute value for ItemDesc, using the alias name ItemDesc.
     * @return the ItemDesc
     */
    public String getItemDesc() {
        return (String)getAttributeInternal(ITEMDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemDesc.
     * @param value value to set the ItemDesc
     */
    public void setItemDesc(String value) {
        setAttributeInternal(ITEMDESC, value);
    }

    /**
     * Gets the attribute value for VersionNo, using the alias name VersionNo.
     * @return the VersionNo
     */
    public Number getVersionNo() {
        return (Number)getAttributeInternal(VERSIONNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionNo.
     * @param value value to set the VersionNo
     */
    public void setVersionNo(Number value) {
        setAttributeInternal(VERSIONNO, value);
    }

    /**
     * Gets the attribute value for VersionDate, using the alias name VersionDate.
     * @return the VersionDate
     */
    public Date getVersionDate() {
        return (Date)getAttributeInternal(VERSIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionDate.
     * @param value value to set the VersionDate
     */
    public void setVersionDate(Date value) {
        setAttributeInternal(VERSIONDATE, value);
    }

    /**
     * Gets the attribute value for Cal, using the alias name Cal.
     * @return the Cal
     */
    public String getCal() {
        return (String)getAttributeInternal(CAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cal.
     * @param value value to set the Cal
     */
    public void setCal(String value) {
        setAttributeInternal(CAL, value);
    }

    /**
     * Gets the attribute value for Cgl, using the alias name Cgl.
     * @return the Cgl
     */
    public String getCgl() {
        return (String)getAttributeInternal(CGL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cgl.
     * @param value value to set the Cgl
     */
    public void setCgl(String value) {
        setAttributeInternal(CGL, value);
    }

    /**
     * Gets the attribute value for Gdl, using the alias name Gdl.
     * @return the Gdl
     */
    public String getGdl() {
        return (String)getAttributeInternal(GDL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Gdl.
     * @param value value to set the Gdl
     */
    public void setGdl(String value) {
        setAttributeInternal(GDL, value);
    }

    /**
     * Gets the attribute value for Gfl, using the alias name Gfl.
     * @return the Gfl
     */
    public String getGfl() {
        return (String)getAttributeInternal(GFL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Gfl.
     * @param value value to set the Gfl
     */
    public void setGfl(String value) {
        setAttributeInternal(GFL, value);
    }

    /**
     * Gets the attribute value for Plan, using the alias name Plan.
     * @return the Plan
     */
    public String getPlan() {
        return (String)getAttributeInternal(PLAN);
    }

    /**
     * Sets <code>value</code> as the attribute value for Plan.
     * @param value value to set the Plan
     */
    public void setPlan(String value) {
        setAttributeInternal(PLAN, value);
    }

    /**
     * Gets the attribute value for RespId, using the alias name RespId.
     * @return the RespId
     */
    
    public Number getRespId() {
        return (Number)getAttributeInternal(RESPID);
        
    }

    /**
     * Sets <code>value</code> as the attribute value for RespId.
     * @param value value to set the RespId
     */
    public void setRespId(Number value) {
        setAttributeInternal(RESPID, value);
    }

    /**
     * Gets the attribute value for SendNotificationTo, using the alias name SendNotificationTo.
     * @return the SendNotificationTo
     */
    public String getSendNotificationTo() {
        return (String)getAttributeInternal(SENDNOTIFICATIONTO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SendNotificationTo.
     * @param value value to set the SendNotificationTo
     */
    public void setSendNotificationTo(String value) {
        setAttributeInternal(SENDNOTIFICATIONTO, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for SampleStatus, using the alias name SampleStatus.
     * @return the SampleStatus
     */
    public String getSampleStatus() {
        return (String)getAttributeInternal(SAMPLESTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for SampleStatus.
     * @param value value to set the SampleStatus
     */
    public void setSampleStatus(String value) {
        setAttributeInternal(SAMPLESTATUS, value);
    }

    /**
     * Gets the attribute value for SubmitStatusMessage, using the alias name SubmitStatusMessage.
     * @return the SubmitStatusMessage
     */
    public String getSubmitStatusMessage() {
        return (String)getAttributeInternal(SUBMITSTATUSMESSAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubmitStatusMessage.
     * @param value value to set the SubmitStatusMessage
     */
    public void setSubmitStatusMessage(String value) {
        setAttributeInternal(SUBMITSTATUSMESSAGE, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the Status
     */
    public Number getStatus() {
        return (Number)getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(Number value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for ExcelFormatChoice, using the alias name ExcelFormatChoice.
     * @return the ExcelFormatChoice
     */
    public String getExcelFormatChoice() {
        return (String)getAttributeInternal(EXCELFORMATCHOICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExcelFormatChoice.
     * @param value value to set the ExcelFormatChoice
     */
    public void setExcelFormatChoice(String value) {
        setAttributeInternal(EXCELFORMATCHOICE, value);
    }

    /**
     * Gets the attribute value for WashingUnit, using the alias name WashingUnit.
     * @return the WashingUnit
     */
    public String getWashingUnit() {
        return (String)getAttributeInternal(WASHINGUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashingUnit.
     * @param value value to set the WashingUnit
     */
    public void setWashingUnit(String value) {
        setAttributeInternal(WASHINGUNIT, value);
    }

    /**
     * Gets the attribute value for RespIdSampleSection, using the alias name RespIdSampleSection.
     * @return the RespIdSampleSection
     */
    public String getRespIdSampleSection() {
        return (String)getAttributeInternal(RESPIDSAMPLESECTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for RespIdSampleSection.
     * @param value value to set the RespIdSampleSection
     */
    public void setRespIdSampleSection(String value) {
        setAttributeInternal(RESPIDSAMPLESECTION, value);
    }

    /**
     * Gets the attribute value for SampleComment, using the alias name SampleComment.
     * @return the SampleComment
     */
    public String getSampleComment() {
        return (String)getAttributeInternal(SAMPLECOMMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for SampleComment.
     * @param value value to set the SampleComment
     */
    public void setSampleComment(String value) {
        setAttributeInternal(SAMPLECOMMENT, value);
    }

    /**
     * Gets the attribute value for Comments, using the alias name Comments.
     * @return the Comments
     */
    public String getComments() {
        return (String)getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Comments.
     * @param value value to set the Comments
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjOntSampleStatusLineEO() {
        return (RowIterator)getAttributeInternal(MNJONTSAMPLESTATUSLINEEO);
    }


    /**
     * @param headerId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number headerId) {
        return new Key(new Object[]{headerId});
    }

    /**
     * Appmodule access code
     *
     */
    
    public ApplicationModule getAppM() {
            DCBindingContainer bindingContainer =
                (DCBindingContainer)BindingContext.getCurrent().getCurrentBindingsEntry();
            //BindingContext bindingContext = BindingContext.getCurrent();
            DCDataControl dc =
                bindingContainer.findDataControl("AppModuleDataControl"); // Name of application module in datacontrolBinding.cpx
            AppModuleImpl appM = (AppModuleImpl)dc.getDataProvider();
            return appM;
        }
        AppModuleImpl appM = (AppModuleImpl)this.getAppM();

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        try{
                /* Sequence Generation Code of Header by PwC */ 
                 setSampleDocNo(new oracle.jbo.domain.Number(getSrNoString()));
                 System.out.println("Recently Created SampleDocNo ---> " + getSrNoString());
                 setCreationDate((Date)Date.getCurrentDate());
                 System.out.println("Recently Created CraetionDate ---> " + (Date)Date.getCurrentDate());
                 oracle.jbo.server.SequenceImpl s = new oracle.jbo.server.SequenceImpl("MNJ_ONT_SAMPLE_STATUS_S",getDBTransaction());          
                 oracle.jbo.domain.Number sVal = s.getSequenceNumber();          
                 setHeaderId(sVal);
                 System.out.println("In Header Recently Created Header ID --> " + sVal);
                 
                 //setRespId(new oracle.jbo.domain.Number(51160));
                 Map sessionScope = ADFContext.getCurrent().getSessionScope();   
                 String respId = (String)sessionScope.get("respId");
                 //String respId = "51159";
                 //String respId = "51160";
                 //String respId = "52666";
        
                 System.out.println("Current Resp Id ---> " +respId);
                 if (respId.equals("51159") || respId.equals("52666") ){
                     System.out.println("@Into US Division Condition");
                     setSendNotificationTo("CAL Sample Section");
                     setRespIdSampleSection("51163");
                     }
                 else if (respId.equals("51160")){
                     System.out.println("@Into EU Division Condition");
                     setSendNotificationTo("GFL Sample Section");
                     setRespIdSampleSection("52626");
                     }
            appM.getDBTransaction().commit();
            
            System.out.println("@Commit Executed in create()...");
            
        } catch(Exception e){
            System.out.println("Exception: " + e.getMessage());
            e.printStackTrace();
            }
                 
                 /* End Sequence Generation Code of Header by PwC */
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

      /**
       * Custom DML update/insert/delete logic here.
       * @param operation the operation type
       * @param e the transaction event
       */
       protected void doDML(int operation, TransactionEvent e) {
             
            Map sessionScope = ADFContext.getCurrent().getSessionScope();   
            String user = (String)sessionScope.get("userId");
            //String user = "6489";
//            String org = (String)sessionScope.get("orgId");
            String respId = (String)sessionScope.get("respId");
            //String respId = "5555";
             if (DML_INSERT == operation){
              
                 try {
                     System.out.println("@In DML_INSERT DODML");
                     //setSampleDocNo(new oracle.jbo.domain.Number(getSrNoString())); 
                     //setCreationDate((Date)Date.getCurrentDate());
                     //System.out.println("@In DML_INSERT DODML AFTER----> CREATION DATE");
                     System.out.println("USER---> " + user);
                    setCreatedBy(new oracle.jbo.domain.Number(user));
                         
//                     System.out.println("ORG---> " + org);
//                     setOrgId(new oracle.jbo.domain.Number(org));
                     System.out.println("@In DML_INSERT DODML AFTER----> CREATED BY");
                     setRespId(new oracle.jbo.domain.Number(respId));
                     System.out.println("@In DML_INSERT DODML AFTER----> RESPID");
                    
                    
                 } catch (SQLException f) {
                     System.out.println(f.getMessage());
                 }
             }
             
           if(DML_UPDATE == operation){
               try {
                   System.out.println("@In DML_UPDATE DODML");
                   setLastUpdateDate((Date)Date.getCurrentDate());
                   System.out.println("@In DML_UPDATE DODML AFTER---->CURRENT DATE");
                   setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                   System.out.println("@In DML_UPDATE DODML AFTER----> LAST UPDATEDD BY");
               } catch (SQLException f) {
                   System.out.println(f.getMessage());
               }
           }
             super.doDML(operation, e);
       }
    
    public int getSrNoString() {
          int srno = 0;
          String stmt = "BEGIN :1 := cust_mnj_ont_pkg.cust_mnj_Sample_Status_srno; end;";
          java.sql.CallableStatement cs =   getDBTransaction().createCallableStatement(stmt, 1);
          try {
              cs.registerOutParameter(1, oracle.jdbc.OracleTypes.VARCHAR);
              cs.execute();
              srno = cs.getInt(1);
              cs.close();
          } catch (Exception e) {
              e.printStackTrace();
          }
          return srno;
        
    }
}
