package model.entity;

import java.sql.SQLException;

import java.util.Map;

import model.services.AppModuleImpl;

import oracle.adf.model.BindingContext;
import oracle.adf.model.binding.DCBindingContainer;
import oracle.adf.model.binding.DCDataControl;
import oracle.adf.share.ADFContext;

import oracle.jbo.ApplicationModule;
import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.NClobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jul 08 11:24:30 BDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjOntSampleStatusLineEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        HeaderId {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getHeaderId();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        LineId {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getLineId();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        StyleName {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getStyleName();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setStyleName((String)value);
            }
        }
        ,
        ItemDescription {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getItemDescription();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setItemDescription((String)value);
            }
        }
        ,
        Status {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getStatus();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        Width {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getWidth();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setWidth((String)value);
            }
        }
        ,
        FabricComposition {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getFabricComposition();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setFabricComposition((String)value);
            }
        }
        ,
        Construction {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getConstruction();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setConstruction((String)value);
            }
        }
        ,
        PackageReceivedDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getPackageReceivedDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setPackageReceivedDate((Date)value);
            }
        }
        ,
        FabricRcvdDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getFabricRcvdDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setFabricRcvdDate((Date)value);
            }
        }
        ,
        Remarks {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getRemarks();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        Fabric {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getFabric();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setFabric((String)value);
            }
        }
        ,
        ShrinkageSendToWash {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getShrinkageSendToWash();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setShrinkageSendToWash((Date)value);
            }
        }
        ,
        ShrinkageRcvdFromWash {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getShrinkageRcvdFromWash();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setShrinkageRcvdFromWash((Date)value);
            }
        }
        ,
        FinalSampleSentToWash {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getFinalSampleSentToWash();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setFinalSampleSentToWash((Date)value);
            }
        }
        ,
        FinalSampleRcvdDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getFinalSampleRcvdDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setFinalSampleRcvdDate((Date)value);
            }
        }
        ,
        SubmittedToMerchandiser {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getSubmittedToMerchandiser();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setSubmittedToMerchandiser((Date)value);
            }
        }
        ,
        WashProcess {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getWashProcess();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setWashProcess((String)value);
            }
        }
        ,
        ChamicalCost {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getChamicalCost();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setChamicalCost((String)value);
            }
        }
        ,
        EimScore {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getEimScore();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setEimScore((String)value);
            }
        }
        ,
        FabricReferenceNo {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getFabricReferenceNo();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setFabricReferenceNo((String)value);
            }
        }
        ,
        ItemCode {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getItemCode();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setItemCode((String)value);
            }
        }
        ,
        ColorWash {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getColorWash();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setColorWash((String)value);
            }
        }
        ,
        WeightValue {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getWeightValue();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setWeightValue((String)value);
            }
        }
        ,
        WeightType {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getWeightType();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setWeightType((String)value);
            }
        }
        ,
        SampleSubmissionDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getSampleSubmissionDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setSampleSubmissionDate((Date)value);
            }
        }
        ,
        AwbNo {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getAwbNo();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setAwbNo((String)value);
            }
        }
        ,
        AwbBillDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getAwbBillDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setAwbBillDate((Date)value);
            }
        }
        ,
        CourierName {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getCourierName();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setCourierName((String)value);
            }
        }
        ,
        ActualtimeArrival {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getActualtimeArrival();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setActualtimeArrival((String)value);
            }
        }
        ,
        DocumentReceiveddate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getDocumentReceiveddate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setDocumentReceiveddate((Date)value);
            }
        }
        ,
        ExpectedReleasedate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getExpectedReleasedate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setExpectedReleasedate((Date)value);
            }
        }
        ,
        FabricSupplier {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getFabricSupplier();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setFabricSupplier((String)value);
            }
        }
        ,
        VendorId {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getVendorId();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setVendorId((Number)value);
            }
        }
        ,
        CmInch {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getCmInch();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setCmInch((String)value);
            }
        }
        ,
        AtaDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getAtaDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setAtaDate((Date)value);
            }
        }
        ,
        WashingUnitName {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getWashingUnitName();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setWashingUnitName((String)value);
            }
        }
        ,
        FabricFlnish {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getFabricFlnish();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setFabricFlnish((String)value);
            }
        }
        ,
        Mill {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getMill();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setMill((String)value);
            }
        }
        ,
        FtdFdsRecDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getFtdFdsRecDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setFtdFdsRecDate((Date)value);
            }
        }
        ,
        FebRecDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getFebRecDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setFebRecDate((Date)value);
            }
        }
        ,
        CommentDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getCommentDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setCommentDate((Date)value);
            }
        }
        ,
        CommentStatus {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getCommentStatus();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setCommentStatus((String)value);
            }
        }
        ,
        Color {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getColor();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setColor((String)value);
            }
        }
        ,
        QuotationReqDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getQuotationReqDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setQuotationReqDate((Date)value);
            }
        }
        ,
        FabricSentDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getFabricSentDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setFabricSentDate((Date)value);
            }
        }
        ,
        SizeNumber {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getSizeNumber();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setSizeNumber((String)value);
            }
        }
        ,
        Qty {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getQty();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setQty((Number)value);
            }
        }
        ,
        HalfLegQty {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getHalfLegQty();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setHalfLegQty((Number)value);
            }
        }
        ,
        Tube {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getTube();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setTube((Number)value);
            }
        }
        ,
        StyleNumber {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getStyleNumber();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setStyleNumber((String)value);
            }
        }
        ,
        Brand {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getBrand();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setBrand((String)value);
            }
        }
        ,
        EndUser {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getEndUser();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setEndUser((String)value);
            }
        }
        ,
        BuyerMerchandiser {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getBuyerMerchandiser();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setBuyerMerchandiser((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Thread {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getThread();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setThread((String)value);
            }
        }
        ,
        Button {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getButton();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setButton((String)value);
            }
        }
        ,
        Rivet {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getRivet();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setRivet((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getAttribute13();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        WashReceived {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getWashReceived();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setWashReceived((String)value);
            }
        }
        ,
        LastInfoReceivedDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getLastInfoReceivedDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setLastInfoReceivedDate((Date)value);
            }
        }
        ,
        LastInfo {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getLastInfo();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setLastInfo((String)value);
            }
        }
        ,
        DropCancelDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getDropCancelDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setDropCancelDate((Date)value);
            }
        }
        ,
        WashSendingDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getWashSendingDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setWashSendingDate((Date)value);
            }
        }
        ,
        ArticalNo {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getArticalNo();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setArticalNo((String)value);
            }
        }
        ,
        SampleRcvDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getSampleRcvDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setSampleRcvDate((Date)value);
            }
        }
        ,
        SampleYardSource {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getSampleYardSource();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setSampleYardSource((String)value);
            }
        }
        ,
        ActualSubDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getActualSubDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setActualSubDate((Date)value);
            }
        }
        ,
        PriceCnf {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getPriceCnf();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setPriceCnf((String)value);
            }
        }
        ,
        SampleType {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getSampleType();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setSampleType((String)value);
            }
        }
        ,
        SampleQty {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getSampleQty();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setSampleQty((Number)value);
            }
        }
        ,
        TotalHalfLegQty {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getTotalHalfLegQty();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setTotalHalfLegQty((Number)value);
            }
        }
        ,
        TotalTubePanelQty {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getTotalTubePanelQty();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setTotalTubePanelQty((Number)value);
            }
        }
        ,
        RequisitionDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getRequisitionDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setRequisitionDate((Date)value);
            }
        }
        ,
        SpecialDetailing {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getSpecialDetailing();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setSpecialDetailing((String)value);
            }
        }
        ,
        YdsStatus {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getYdsStatus();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setYdsStatus((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        Department {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getDepartment();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setDepartment((String)value);
            }
        }
        ,
        DesignSheet {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getDesignSheet();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setDesignSheet((String)value);
            }
        }
        ,
        WashInstruction {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getWashInstruction();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setWashInstruction((String)value);
            }
        }
        ,
        StyleDescription {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getStyleDescription();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setStyleDescription((String)value);
            }
        }
        ,
        SampleQtyDetails {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getSampleQtyDetails();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setSampleQtyDetails((String)value);
            }
        }
        ,
        Buyer {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getBuyer();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setBuyer((String)value);
            }
        }
        ,
        Composition {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getComposition();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setComposition((String)value);
            }
        }
        ,
        CutableWidth {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getCutableWidth();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setCutableWidth((String)value);
            }
        }
        ,
        FabricRequestDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getFabricRequestDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setFabricRequestDate((Date)value);
            }
        }
        ,
        InventoryItemId {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getInventoryItemId();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setInventoryItemId((String)value);
            }
        }
        ,
        SourceSupplier {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getSourceSupplier();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setSourceSupplier((String)value);
            }
        }
        ,
        WashReceivedDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getWashReceivedDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setWashReceivedDate((Date)value);
            }
        }
        ,
        SampleDocNo {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getSampleDocNo();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setSampleDocNo((Number)value);
            }
        }
        ,
        SampleDeadlineDate {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getSampleDeadlineDate();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setSampleDeadlineDate((Date)value);
            }
        }
        ,
        InsideWb {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getInsideWb();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setInsideWb((String)value);
            }
        }
        ,
        PocketingLeft {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getPocketingLeft();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setPocketingLeft((String)value);
            }
        }
        ,
        PocketingRight {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getPocketingRight();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setPocketingRight((String)value);
            }
        }
        ,
        WashingUnit {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getWashingUnit();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setWashingUnit((String)value);
            }
        }
        ,
        Serial {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getSerial();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setSerial((Number)value);
            }
        }
        ,
        SpecificationPattern {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getSpecificationPattern();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setSpecificationPattern((String)value);
            }
        }
        ,
        Zipper {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getZipper();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setZipper((String)value);
            }
        }
        ,
        MockupQty {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getMockupQty();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setMockupQty((Number)value);
            }
        }
        ,
        MnjOntSampleStatusDetailEO {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getMnjOntSampleStatusDetailEO();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjOntSampleStatusEO {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getMnjOntSampleStatusEO();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setMnjOntSampleStatusEO((MnjOntSampleStatusEOImpl)value);
            }
        }
        ,
        MnjOntSampleStatusViewOnlyEO {
            public Object get(MnjOntSampleStatusLineEOImpl obj) {
                return obj.getMnjOntSampleStatusViewOnlyEO();
            }

            public void put(MnjOntSampleStatusLineEOImpl obj, Object value) {
                obj.setMnjOntSampleStatusViewOnlyEO((EntityImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjOntSampleStatusLineEOImpl object);

        public abstract void put(MnjOntSampleStatusLineEOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    //public static final int MNJONTSAMPLESTATUSEO1 = AttributesEnum.MnjOntSampleStatusEO1.index();


    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int STYLENAME = AttributesEnum.StyleName.index();
    public static final int ITEMDESCRIPTION = AttributesEnum.ItemDescription.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int WIDTH = AttributesEnum.Width.index();
    public static final int FABRICCOMPOSITION = AttributesEnum.FabricComposition.index();
    public static final int CONSTRUCTION = AttributesEnum.Construction.index();
    public static final int PACKAGERECEIVEDDATE = AttributesEnum.PackageReceivedDate.index();
    public static final int FABRICRCVDDATE = AttributesEnum.FabricRcvdDate.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int FABRIC = AttributesEnum.Fabric.index();
    public static final int SHRINKAGESENDTOWASH = AttributesEnum.ShrinkageSendToWash.index();
    public static final int SHRINKAGERCVDFROMWASH = AttributesEnum.ShrinkageRcvdFromWash.index();
    public static final int FINALSAMPLESENTTOWASH = AttributesEnum.FinalSampleSentToWash.index();
    public static final int FINALSAMPLERCVDDATE = AttributesEnum.FinalSampleRcvdDate.index();
    public static final int SUBMITTEDTOMERCHANDISER = AttributesEnum.SubmittedToMerchandiser.index();
    public static final int WASHPROCESS = AttributesEnum.WashProcess.index();
    public static final int CHAMICALCOST = AttributesEnum.ChamicalCost.index();
    public static final int EIMSCORE = AttributesEnum.EimScore.index();
    public static final int FABRICREFERENCENO = AttributesEnum.FabricReferenceNo.index();
    public static final int ITEMCODE = AttributesEnum.ItemCode.index();
    public static final int COLORWASH = AttributesEnum.ColorWash.index();
    public static final int WEIGHTVALUE = AttributesEnum.WeightValue.index();
    public static final int WEIGHTTYPE = AttributesEnum.WeightType.index();
    public static final int SAMPLESUBMISSIONDATE = AttributesEnum.SampleSubmissionDate.index();
    public static final int AWBNO = AttributesEnum.AwbNo.index();
    public static final int AWBBILLDATE = AttributesEnum.AwbBillDate.index();
    public static final int COURIERNAME = AttributesEnum.CourierName.index();
    public static final int ACTUALTIMEARRIVAL = AttributesEnum.ActualtimeArrival.index();
    public static final int DOCUMENTRECEIVEDDATE = AttributesEnum.DocumentReceiveddate.index();
    public static final int EXPECTEDRELEASEDATE = AttributesEnum.ExpectedReleasedate.index();
    public static final int FABRICSUPPLIER = AttributesEnum.FabricSupplier.index();
    public static final int VENDORID = AttributesEnum.VendorId.index();
    public static final int CMINCH = AttributesEnum.CmInch.index();
    public static final int ATADATE = AttributesEnum.AtaDate.index();
    public static final int WASHINGUNITNAME = AttributesEnum.WashingUnitName.index();
    public static final int FABRICFLNISH = AttributesEnum.FabricFlnish.index();
    public static final int MILL = AttributesEnum.Mill.index();
    public static final int FTDFDSRECDATE = AttributesEnum.FtdFdsRecDate.index();
    public static final int FEBRECDATE = AttributesEnum.FebRecDate.index();
    public static final int COMMENTDATE = AttributesEnum.CommentDate.index();
    public static final int COMMENTSTATUS = AttributesEnum.CommentStatus.index();
    public static final int COLOR = AttributesEnum.Color.index();
    public static final int QUOTATIONREQDATE = AttributesEnum.QuotationReqDate.index();
    public static final int FABRICSENTDATE = AttributesEnum.FabricSentDate.index();
    public static final int SIZENUMBER = AttributesEnum.SizeNumber.index();
    public static final int QTY = AttributesEnum.Qty.index();
    public static final int HALFLEGQTY = AttributesEnum.HalfLegQty.index();
    public static final int TUBE = AttributesEnum.Tube.index();
    public static final int STYLENUMBER = AttributesEnum.StyleNumber.index();
    public static final int BRAND = AttributesEnum.Brand.index();
    public static final int ENDUSER = AttributesEnum.EndUser.index();
    public static final int BUYERMERCHANDISER = AttributesEnum.BuyerMerchandiser.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int THREAD = AttributesEnum.Thread.index();
    public static final int BUTTON = AttributesEnum.Button.index();
    public static final int RIVET = AttributesEnum.Rivet.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int WASHRECEIVED = AttributesEnum.WashReceived.index();
    public static final int LASTINFORECEIVEDDATE = AttributesEnum.LastInfoReceivedDate.index();
    public static final int LASTINFO = AttributesEnum.LastInfo.index();
    public static final int DROPCANCELDATE = AttributesEnum.DropCancelDate.index();
    public static final int WASHSENDINGDATE = AttributesEnum.WashSendingDate.index();
    public static final int ARTICALNO = AttributesEnum.ArticalNo.index();
    public static final int SAMPLERCVDATE = AttributesEnum.SampleRcvDate.index();
    public static final int SAMPLEYARDSOURCE = AttributesEnum.SampleYardSource.index();
    public static final int ACTUALSUBDATE = AttributesEnum.ActualSubDate.index();
    public static final int PRICECNF = AttributesEnum.PriceCnf.index();
    public static final int SAMPLETYPE = AttributesEnum.SampleType.index();
    public static final int SAMPLEQTY = AttributesEnum.SampleQty.index();
    public static final int TOTALHALFLEGQTY = AttributesEnum.TotalHalfLegQty.index();
    public static final int TOTALTUBEPANELQTY = AttributesEnum.TotalTubePanelQty.index();
    public static final int REQUISITIONDATE = AttributesEnum.RequisitionDate.index();
    public static final int SPECIALDETAILING = AttributesEnum.SpecialDetailing.index();
    public static final int YDSSTATUS = AttributesEnum.YdsStatus.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int DEPARTMENT = AttributesEnum.Department.index();
    public static final int DESIGNSHEET = AttributesEnum.DesignSheet.index();
    public static final int WASHINSTRUCTION = AttributesEnum.WashInstruction.index();
    public static final int STYLEDESCRIPTION = AttributesEnum.StyleDescription.index();
    public static final int SAMPLEQTYDETAILS = AttributesEnum.SampleQtyDetails.index();
    public static final int BUYER = AttributesEnum.Buyer.index();
    public static final int COMPOSITION = AttributesEnum.Composition.index();
    public static final int CUTABLEWIDTH = AttributesEnum.CutableWidth.index();
    public static final int FABRICREQUESTDATE = AttributesEnum.FabricRequestDate.index();
    public static final int INVENTORYITEMID = AttributesEnum.InventoryItemId.index();
    public static final int SOURCESUPPLIER = AttributesEnum.SourceSupplier.index();
    public static final int WASHRECEIVEDDATE = AttributesEnum.WashReceivedDate.index();
    public static final int SAMPLEDOCNO = AttributesEnum.SampleDocNo.index();
    public static final int SAMPLEDEADLINEDATE = AttributesEnum.SampleDeadlineDate.index();
    public static final int INSIDEWB = AttributesEnum.InsideWb.index();
    public static final int POCKETINGLEFT = AttributesEnum.PocketingLeft.index();
    public static final int POCKETINGRIGHT = AttributesEnum.PocketingRight.index();
    public static final int WASHINGUNIT = AttributesEnum.WashingUnit.index();
    public static final int SERIAL = AttributesEnum.Serial.index();
    public static final int SPECIFICATIONPATTERN = AttributesEnum.SpecificationPattern.index();
    public static final int ZIPPER = AttributesEnum.Zipper.index();
    public static final int MOCKUPQTY = AttributesEnum.MockupQty.index();
    public static final int MNJONTSAMPLESTATUSDETAILEO = AttributesEnum.MnjOntSampleStatusDetailEO.index();
    public static final int MNJONTSAMPLESTATUSEO = AttributesEnum.MnjOntSampleStatusEO.index();
    public static final int MNJONTSAMPLESTATUSVIEWONLYEO = AttributesEnum.MnjOntSampleStatusViewOnlyEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjOntSampleStatusLineEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.entity.MnjOntSampleStatusLineEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for LineId, using the alias name LineId.
     * @return the LineId
     */
    public Number getLineId() {
        return (Number)getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineId.
     * @param value value to set the LineId
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for StyleName, using the alias name StyleName.
     * @return the StyleName
     */
    public String getStyleName() {
        return (String)getAttributeInternal(STYLENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for StyleName.
     * @param value value to set the StyleName
     */
    public void setStyleName(String value) {
        setAttributeInternal(STYLENAME, value);
    }

    /**
     * Gets the attribute value for ItemDescription, using the alias name ItemDescription.
     * @return the ItemDescription
     */
    public String getItemDescription() {
        return (String)getAttributeInternal(ITEMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemDescription.
     * @param value value to set the ItemDescription
     */
    public void setItemDescription(String value) {
        setAttributeInternal(ITEMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for Width, using the alias name Width.
     * @return the Width
     */
    public String getWidth() {
        return (String)getAttributeInternal(WIDTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Width.
     * @param value value to set the Width
     */
    public void setWidth(String value) {
        setAttributeInternal(WIDTH, value);
    }

    /**
     * Gets the attribute value for FabricComposition, using the alias name FabricComposition.
     * @return the FabricComposition
     */
    public String getFabricComposition() {
        return (String)getAttributeInternal(FABRICCOMPOSITION);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabricComposition.
     * @param value value to set the FabricComposition
     */
    public void setFabricComposition(String value) {
        setAttributeInternal(FABRICCOMPOSITION, value);
    }

    /**
     * Gets the attribute value for Construction, using the alias name Construction.
     * @return the Construction
     */
    public String getConstruction() {
        return (String)getAttributeInternal(CONSTRUCTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Construction.
     * @param value value to set the Construction
     */
    public void setConstruction(String value) {
        setAttributeInternal(CONSTRUCTION, value);
    }

    /**
     * Gets the attribute value for PackageReceivedDate, using the alias name PackageReceivedDate.
     * @return the PackageReceivedDate
     */
    public Date getPackageReceivedDate() {
        return (Date)getAttributeInternal(PACKAGERECEIVEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PackageReceivedDate.
     * @param value value to set the PackageReceivedDate
     */
    public void setPackageReceivedDate(Date value) {
        setAttributeInternal(PACKAGERECEIVEDDATE, value);
    }

    /**
     * Gets the attribute value for FabricRcvdDate, using the alias name FabricRcvdDate.
     * @return the FabricRcvdDate
     */
    public Date getFabricRcvdDate() {
        return (Date)getAttributeInternal(FABRICRCVDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabricRcvdDate.
     * @param value value to set the FabricRcvdDate
     */
    public void setFabricRcvdDate(Date value) {
        setAttributeInternal(FABRICRCVDDATE, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for Fabric, using the alias name Fabric.
     * @return the Fabric
     */
    public String getFabric() {
        return (String)getAttributeInternal(FABRIC);
    }

    /**
     * Sets <code>value</code> as the attribute value for Fabric.
     * @param value value to set the Fabric
     */
    public void setFabric(String value) {
        setAttributeInternal(FABRIC, value);
    }

    /**
     * Gets the attribute value for ShrinkageSendToWash, using the alias name ShrinkageSendToWash.
     * @return the ShrinkageSendToWash
     */
    public Date getShrinkageSendToWash() {
        return (Date)getAttributeInternal(SHRINKAGESENDTOWASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShrinkageSendToWash.
     * @param value value to set the ShrinkageSendToWash
     */
    public void setShrinkageSendToWash(Date value) {
        setAttributeInternal(SHRINKAGESENDTOWASH, value);
    }

    /**
     * Gets the attribute value for ShrinkageRcvdFromWash, using the alias name ShrinkageRcvdFromWash.
     * @return the ShrinkageRcvdFromWash
     */
    public Date getShrinkageRcvdFromWash() {
        return (Date)getAttributeInternal(SHRINKAGERCVDFROMWASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShrinkageRcvdFromWash.
     * @param value value to set the ShrinkageRcvdFromWash
     */
    public void setShrinkageRcvdFromWash(Date value) {
        setAttributeInternal(SHRINKAGERCVDFROMWASH, value);
    }

    /**
     * Gets the attribute value for FinalSampleSentToWash, using the alias name FinalSampleSentToWash.
     * @return the FinalSampleSentToWash
     */
    public Date getFinalSampleSentToWash() {
        return (Date)getAttributeInternal(FINALSAMPLESENTTOWASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for FinalSampleSentToWash.
     * @param value value to set the FinalSampleSentToWash
     */
    public void setFinalSampleSentToWash(Date value) {
        setAttributeInternal(FINALSAMPLESENTTOWASH, value);
    }

    /**
     * Gets the attribute value for FinalSampleRcvdDate, using the alias name FinalSampleRcvdDate.
     * @return the FinalSampleRcvdDate
     */
    public Date getFinalSampleRcvdDate() {
        return (Date)getAttributeInternal(FINALSAMPLERCVDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FinalSampleRcvdDate.
     * @param value value to set the FinalSampleRcvdDate
     */
    public void setFinalSampleRcvdDate(Date value) {
        setAttributeInternal(FINALSAMPLERCVDDATE, value);
    }

    /**
     * Gets the attribute value for SubmittedToMerchandiser, using the alias name SubmittedToMerchandiser.
     * @return the SubmittedToMerchandiser
     */
    public Date getSubmittedToMerchandiser() {
        return (Date)getAttributeInternal(SUBMITTEDTOMERCHANDISER);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubmittedToMerchandiser.
     * @param value value to set the SubmittedToMerchandiser
     */
    public void setSubmittedToMerchandiser(Date value) {
        setAttributeInternal(SUBMITTEDTOMERCHANDISER, value);
    }

    /**
     * Gets the attribute value for WashProcess, using the alias name WashProcess.
     * @return the WashProcess
     */
    public String getWashProcess() {
        return (String)getAttributeInternal(WASHPROCESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashProcess.
     * @param value value to set the WashProcess
     */
    public void setWashProcess(String value) {
        setAttributeInternal(WASHPROCESS, value);
    }

    /**
     * Gets the attribute value for ChamicalCost, using the alias name ChamicalCost.
     * @return the ChamicalCost
     */
    public String getChamicalCost() {
        return (String)getAttributeInternal(CHAMICALCOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChamicalCost.
     * @param value value to set the ChamicalCost
     */
    public void setChamicalCost(String value) {
        setAttributeInternal(CHAMICALCOST, value);
    }

    /**
     * Gets the attribute value for EimScore, using the alias name EimScore.
     * @return the EimScore
     */
    public String getEimScore() {
        return (String)getAttributeInternal(EIMSCORE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EimScore.
     * @param value value to set the EimScore
     */
    public void setEimScore(String value) {
        setAttributeInternal(EIMSCORE, value);
    }

    /**
     * Gets the attribute value for FabricReferenceNo, using the alias name FabricReferenceNo.
     * @return the FabricReferenceNo
     */
    public String getFabricReferenceNo() {
        return (String)getAttributeInternal(FABRICREFERENCENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabricReferenceNo.
     * @param value value to set the FabricReferenceNo
     */
    public void setFabricReferenceNo(String value) {
        setAttributeInternal(FABRICREFERENCENO, value);
    }

    /**
     * Gets the attribute value for ItemCode, using the alias name ItemCode.
     * @return the ItemCode
     */
    public String getItemCode() {
        return (String)getAttributeInternal(ITEMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemCode.
     * @param value value to set the ItemCode
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**
     * Gets the attribute value for ColorWash, using the alias name ColorWash.
     * @return the ColorWash
     */
    public String getColorWash() {
        return (String)getAttributeInternal(COLORWASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for ColorWash.
     * @param value value to set the ColorWash
     */
    public void setColorWash(String value) {
        setAttributeInternal(COLORWASH, value);
    }

    /**
     * Gets the attribute value for WeightValue, using the alias name WeightValue.
     * @return the WeightValue
     */
    public String getWeightValue() {
        return (String)getAttributeInternal(WEIGHTVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WeightValue.
     * @param value value to set the WeightValue
     */
    public void setWeightValue(String value) {
        setAttributeInternal(WEIGHTVALUE, value);
    }

    /**
     * Gets the attribute value for WeightType, using the alias name WeightType.
     * @return the WeightType
     */
    public String getWeightType() {
        return (String)getAttributeInternal(WEIGHTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WeightType.
     * @param value value to set the WeightType
     */
    public void setWeightType(String value) {
        setAttributeInternal(WEIGHTTYPE, value);
    }

    /**
     * Gets the attribute value for SampleSubmissionDate, using the alias name SampleSubmissionDate.
     * @return the SampleSubmissionDate
     */
    public Date getSampleSubmissionDate() {
        return (Date)getAttributeInternal(SAMPLESUBMISSIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SampleSubmissionDate.
     * @param value value to set the SampleSubmissionDate
     */
    public void setSampleSubmissionDate(Date value) {
        setAttributeInternal(SAMPLESUBMISSIONDATE, value);
    }

    /**
     * Gets the attribute value for AwbNo, using the alias name AwbNo.
     * @return the AwbNo
     */
    public String getAwbNo() {
        return (String)getAttributeInternal(AWBNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for AwbNo.
     * @param value value to set the AwbNo
     */
    public void setAwbNo(String value) {
        setAttributeInternal(AWBNO, value);
    }

    /**
     * Gets the attribute value for AwbBillDate, using the alias name AwbBillDate.
     * @return the AwbBillDate
     */
    public Date getAwbBillDate() {
        return (Date)getAttributeInternal(AWBBILLDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AwbBillDate.
     * @param value value to set the AwbBillDate
     */
    public void setAwbBillDate(Date value) {
        setAttributeInternal(AWBBILLDATE, value);
    }

    /**
     * Gets the attribute value for CourierName, using the alias name CourierName.
     * @return the CourierName
     */
    public String getCourierName() {
        return (String)getAttributeInternal(COURIERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CourierName.
     * @param value value to set the CourierName
     */
    public void setCourierName(String value) {
        setAttributeInternal(COURIERNAME, value);
    }

    /**
     * Gets the attribute value for ActualtimeArrival, using the alias name ActualtimeArrival.
     * @return the ActualtimeArrival
     */
    public String getActualtimeArrival() {
        return (String)getAttributeInternal(ACTUALTIMEARRIVAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActualtimeArrival.
     * @param value value to set the ActualtimeArrival
     */
    public void setActualtimeArrival(String value) {
        setAttributeInternal(ACTUALTIMEARRIVAL, value);
    }

    /**
     * Gets the attribute value for DocumentReceiveddate, using the alias name DocumentReceiveddate.
     * @return the DocumentReceiveddate
     */
    public Date getDocumentReceiveddate() {
        return (Date)getAttributeInternal(DOCUMENTRECEIVEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocumentReceiveddate.
     * @param value value to set the DocumentReceiveddate
     */
    public void setDocumentReceiveddate(Date value) {
        setAttributeInternal(DOCUMENTRECEIVEDDATE, value);
    }

    /**
     * Gets the attribute value for ExpectedReleasedate, using the alias name ExpectedReleasedate.
     * @return the ExpectedReleasedate
     */
    public Date getExpectedReleasedate() {
        return (Date)getAttributeInternal(EXPECTEDRELEASEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpectedReleasedate.
     * @param value value to set the ExpectedReleasedate
     */
    public void setExpectedReleasedate(Date value) {
        setAttributeInternal(EXPECTEDRELEASEDATE, value);
    }

    /**
     * Gets the attribute value for FabricSupplier, using the alias name FabricSupplier.
     * @return the FabricSupplier
     */
    public String getFabricSupplier() {
        return (String)getAttributeInternal(FABRICSUPPLIER);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabricSupplier.
     * @param value value to set the FabricSupplier
     */
    public void setFabricSupplier(String value) {
        setAttributeInternal(FABRICSUPPLIER, value);
    }

    /**
     * Gets the attribute value for VendorId, using the alias name VendorId.
     * @return the VendorId
     */
    public Number getVendorId() {
        return (Number)getAttributeInternal(VENDORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for VendorId.
     * @param value value to set the VendorId
     */
    public void setVendorId(Number value) {
        setAttributeInternal(VENDORID, value);
    }

    /**
     * Gets the attribute value for CmInch, using the alias name CmInch.
     * @return the CmInch
     */
    public String getCmInch() {
        return (String)getAttributeInternal(CMINCH);
    }

    /**
     * Sets <code>value</code> as the attribute value for CmInch.
     * @param value value to set the CmInch
     */
    public void setCmInch(String value) {
        setAttributeInternal(CMINCH, value);
    }

    /**
     * Gets the attribute value for AtaDate, using the alias name AtaDate.
     * @return the AtaDate
     */
    public Date getAtaDate() {
        return (Date)getAttributeInternal(ATADATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AtaDate.
     * @param value value to set the AtaDate
     */
    public void setAtaDate(Date value) {
        setAttributeInternal(ATADATE, value);
    }

    /**
     * Gets the attribute value for WashingUnitName, using the alias name WashingUnitName.
     * @return the WashingUnitName
     */
    public String getWashingUnitName() {
        return (String)getAttributeInternal(WASHINGUNITNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashingUnitName.
     * @param value value to set the WashingUnitName
     */
    public void setWashingUnitName(String value) {
        setAttributeInternal(WASHINGUNITNAME, value);
    }

    /**
     * Gets the attribute value for FabricFlnish, using the alias name FabricFlnish.
     * @return the FabricFlnish
     */
    public String getFabricFlnish() {
        return (String)getAttributeInternal(FABRICFLNISH);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabricFlnish.
     * @param value value to set the FabricFlnish
     */
    public void setFabricFlnish(String value) {
        setAttributeInternal(FABRICFLNISH, value);
    }

    /**
     * Gets the attribute value for Mill, using the alias name Mill.
     * @return the Mill
     */
    public String getMill() {
        return (String)getAttributeInternal(MILL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Mill.
     * @param value value to set the Mill
     */
    public void setMill(String value) {
        setAttributeInternal(MILL, value);
    }

    /**
     * Gets the attribute value for FtdFdsRecDate, using the alias name FtdFdsRecDate.
     * @return the FtdFdsRecDate
     */
    public Date getFtdFdsRecDate() {
        return (Date)getAttributeInternal(FTDFDSRECDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FtdFdsRecDate.
     * @param value value to set the FtdFdsRecDate
     */
    public void setFtdFdsRecDate(Date value) {
        setAttributeInternal(FTDFDSRECDATE, value);
    }

    /**
     * Gets the attribute value for FebRecDate, using the alias name FebRecDate.
     * @return the FebRecDate
     */
    public Date getFebRecDate() {
        return (Date)getAttributeInternal(FEBRECDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FebRecDate.
     * @param value value to set the FebRecDate
     */
    public void setFebRecDate(Date value) {
        setAttributeInternal(FEBRECDATE, value);
    }

    /**
     * Gets the attribute value for CommentDate, using the alias name CommentDate.
     * @return the CommentDate
     */
    public Date getCommentDate() {
        return (Date)getAttributeInternal(COMMENTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommentDate.
     * @param value value to set the CommentDate
     */
    public void setCommentDate(Date value) {
        setAttributeInternal(COMMENTDATE, value);
    }

    /**
     * Gets the attribute value for CommentStatus, using the alias name CommentStatus.
     * @return the CommentStatus
     */
    public String getCommentStatus() {
        return (String)getAttributeInternal(COMMENTSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommentStatus.
     * @param value value to set the CommentStatus
     */
    public void setCommentStatus(String value) {
        setAttributeInternal(COMMENTSTATUS, value);
    }

    /**
     * Gets the attribute value for Color, using the alias name Color.
     * @return the Color
     */
    public String getColor() {
        return (String)getAttributeInternal(COLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Color.
     * @param value value to set the Color
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**
     * Gets the attribute value for QuotationReqDate, using the alias name QuotationReqDate.
     * @return the QuotationReqDate
     */
    public Date getQuotationReqDate() {
        return (Date)getAttributeInternal(QUOTATIONREQDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for QuotationReqDate.
     * @param value value to set the QuotationReqDate
     */
    public void setQuotationReqDate(Date value) {
        setAttributeInternal(QUOTATIONREQDATE, value);
    }

    /**
     * Gets the attribute value for FabricSentDate, using the alias name FabricSentDate.
     * @return the FabricSentDate
     */
    public Date getFabricSentDate() {
        return (Date)getAttributeInternal(FABRICSENTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabricSentDate.
     * @param value value to set the FabricSentDate
     */
    public void setFabricSentDate(Date value) {
        setAttributeInternal(FABRICSENTDATE, value);
    }

    /**
     * Gets the attribute value for SizeNumber, using the alias name SizeNumber.
     * @return the SizeNumber
     */
    public String getSizeNumber() {
        return (String)getAttributeInternal(SIZENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeNumber.
     * @param value value to set the SizeNumber
     */
    public void setSizeNumber(String value) {
        setAttributeInternal(SIZENUMBER, value);
    }

    /**
     * Gets the attribute value for Qty, using the alias name Qty.
     * @return the Qty
     */
    public Number getQty() {
        return (Number)getAttributeInternal(QTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Qty.
     * @param value value to set the Qty
     */
    public void setQty(Number value) {
        setAttributeInternal(QTY, value);
    }

    /**
     * Gets the attribute value for HalfLegQty, using the alias name HalfLegQty.
     * @return the HalfLegQty
     */
    public Number getHalfLegQty() {
        return (Number)getAttributeInternal(HALFLEGQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for HalfLegQty.
     * @param value value to set the HalfLegQty
     */
    public void setHalfLegQty(Number value) {
        setAttributeInternal(HALFLEGQTY, value);
    }

    /**
     * Gets the attribute value for Tube, using the alias name Tube.
     * @return the Tube
     */
    public Number getTube() {
        return (Number)getAttributeInternal(TUBE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Tube.
     * @param value value to set the Tube
     */
    public void setTube(Number value) {
        setAttributeInternal(TUBE, value);
    }

    /**
     * Gets the attribute value for StyleNumber, using the alias name StyleNumber.
     * @return the StyleNumber
     */
    public String getStyleNumber() {
        return (String)getAttributeInternal(STYLENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for StyleNumber.
     * @param value value to set the StyleNumber
     */
    public void setStyleNumber(String value) {
        setAttributeInternal(STYLENUMBER, value);
    }

    /**
     * Gets the attribute value for Brand, using the alias name Brand.
     * @return the Brand
     */
    public String getBrand() {
        return (String)getAttributeInternal(BRAND);
    }

    /**
     * Sets <code>value</code> as the attribute value for Brand.
     * @param value value to set the Brand
     */
    public void setBrand(String value) {
        setAttributeInternal(BRAND, value);
    }

    /**
     * Gets the attribute value for EndUser, using the alias name EndUser.
     * @return the EndUser
     */
    public String getEndUser() {
        return (String)getAttributeInternal(ENDUSER);
    }

    /**
     * Sets <code>value</code> as the attribute value for EndUser.
     * @param value value to set the EndUser
     */
    public void setEndUser(String value) {
        setAttributeInternal(ENDUSER, value);
    }

    /**
     * Gets the attribute value for BuyerMerchandiser, using the alias name BuyerMerchandiser.
     * @return the BuyerMerchandiser
     */
    public String getBuyerMerchandiser() {
        return (String)getAttributeInternal(BUYERMERCHANDISER);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuyerMerchandiser.
     * @param value value to set the BuyerMerchandiser
     */
    public void setBuyerMerchandiser(String value) {
        setAttributeInternal(BUYERMERCHANDISER, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Thread, using the alias name Thread.
     * @return the Thread
     */
    public String getThread() {
        return (String)getAttributeInternal(THREAD);
    }

    /**
     * Sets <code>value</code> as the attribute value for Thread.
     * @param value value to set the Thread
     */
    public void setThread(String value) {
        setAttributeInternal(THREAD, value);
    }

    /**
     * Gets the attribute value for Button, using the alias name Button.
     * @return the Button
     */
    public String getButton() {
        return (String)getAttributeInternal(BUTTON);
    }

    /**
     * Sets <code>value</code> as the attribute value for Button.
     * @param value value to set the Button
     */
    public void setButton(String value) {
        setAttributeInternal(BUTTON, value);
    }

    /**
     * Gets the attribute value for Rivet, using the alias name Rivet.
     * @return the Rivet
     */
    public String getRivet() {
        return (String)getAttributeInternal(RIVET);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rivet.
     * @param value value to set the Rivet
     */
    public void setRivet(String value) {
        setAttributeInternal(RIVET, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for WashReceived, using the alias name WashReceived.
     * @return the WashReceived
     */
    public String getWashReceived() {
        return (String)getAttributeInternal(WASHRECEIVED);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashReceived.
     * @param value value to set the WashReceived
     */
    public void setWashReceived(String value) {
        setAttributeInternal(WASHRECEIVED, value);
    }

    /**
     * Gets the attribute value for LastInfoReceivedDate, using the alias name LastInfoReceivedDate.
     * @return the LastInfoReceivedDate
     */
    public Date getLastInfoReceivedDate() {
        return (Date)getAttributeInternal(LASTINFORECEIVEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastInfoReceivedDate.
     * @param value value to set the LastInfoReceivedDate
     */
    public void setLastInfoReceivedDate(Date value) {
        setAttributeInternal(LASTINFORECEIVEDDATE, value);
    }

    /**
     * Gets the attribute value for LastInfo, using the alias name LastInfo.
     * @return the LastInfo
     */
    public String getLastInfo() {
        return (String)getAttributeInternal(LASTINFO);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastInfo.
     * @param value value to set the LastInfo
     */
    public void setLastInfo(String value) {
        setAttributeInternal(LASTINFO, value);
    }

    /**
     * Gets the attribute value for DropCancelDate, using the alias name DropCancelDate.
     * @return the DropCancelDate
     */
    public Date getDropCancelDate() {
        return (Date)getAttributeInternal(DROPCANCELDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DropCancelDate.
     * @param value value to set the DropCancelDate
     */
    public void setDropCancelDate(Date value) {
        setAttributeInternal(DROPCANCELDATE, value);
    }

    /**
     * Gets the attribute value for WashSendingDate, using the alias name WashSendingDate.
     * @return the WashSendingDate
     */
    public Date getWashSendingDate() {
        return (Date)getAttributeInternal(WASHSENDINGDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashSendingDate.
     * @param value value to set the WashSendingDate
     */
    public void setWashSendingDate(Date value) {
        setAttributeInternal(WASHSENDINGDATE, value);
    }

    /**
     * Gets the attribute value for ArticalNo, using the alias name ArticalNo.
     * @return the ArticalNo
     */
    public String getArticalNo() {
        return (String)getAttributeInternal(ARTICALNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ArticalNo.
     * @param value value to set the ArticalNo
     */
    public void setArticalNo(String value) {
        setAttributeInternal(ARTICALNO, value);
    }

    /**
     * Gets the attribute value for SampleRcvDate, using the alias name SampleRcvDate.
     * @return the SampleRcvDate
     */
    public Date getSampleRcvDate() {
        return (Date)getAttributeInternal(SAMPLERCVDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SampleRcvDate.
     * @param value value to set the SampleRcvDate
     */
    public void setSampleRcvDate(Date value) {
        setAttributeInternal(SAMPLERCVDATE, value);
    }

    /**
     * Gets the attribute value for SampleYardSource, using the alias name SampleYardSource.
     * @return the SampleYardSource
     */
    public String getSampleYardSource() {
        return (String)getAttributeInternal(SAMPLEYARDSOURCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SampleYardSource.
     * @param value value to set the SampleYardSource
     */
    public void setSampleYardSource(String value) {
        setAttributeInternal(SAMPLEYARDSOURCE, value);
    }

    /**
     * Gets the attribute value for ActualSubDate, using the alias name ActualSubDate.
     * @return the ActualSubDate
     */
    public Date getActualSubDate() {
        return (Date)getAttributeInternal(ACTUALSUBDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActualSubDate.
     * @param value value to set the ActualSubDate
     */
    public void setActualSubDate(Date value) {
        setAttributeInternal(ACTUALSUBDATE, value);
    }

    /**
     * Gets the attribute value for PriceCnf, using the alias name PriceCnf.
     * @return the PriceCnf
     */
    public String getPriceCnf() {
        return (String)getAttributeInternal(PRICECNF);
    }

    /**
     * Sets <code>value</code> as the attribute value for PriceCnf.
     * @param value value to set the PriceCnf
     */
    public void setPriceCnf(String value) {
        setAttributeInternal(PRICECNF, value);
    }

    /**
     * Gets the attribute value for SampleType, using the alias name SampleType.
     * @return the SampleType
     */
    public String getSampleType() {
        return (String)getAttributeInternal(SAMPLETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SampleType.
     * @param value value to set the SampleType
     */
    public void setSampleType(String value) {
        setAttributeInternal(SAMPLETYPE, value);
    }

    /**
     * Gets the attribute value for SampleQty, using the alias name SampleQty.
     * @return the SampleQty
     */
    public Number getSampleQty() {
        return (Number)getAttributeInternal(SAMPLEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SampleQty.
     * @param value value to set the SampleQty
     */
    public void setSampleQty(Number value) {
        setAttributeInternal(SAMPLEQTY, value);
    }

    /**
     * Gets the attribute value for TotalHalfLegQty, using the alias name TotalHalfLegQty.
     * @return the TotalHalfLegQty
     */
    public Number getTotalHalfLegQty() {
        return (Number)getAttributeInternal(TOTALHALFLEGQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalHalfLegQty.
     * @param value value to set the TotalHalfLegQty
     */
    public void setTotalHalfLegQty(Number value) {
        setAttributeInternal(TOTALHALFLEGQTY, value);
    }

    /**
     * Gets the attribute value for TotalTubePanelQty, using the alias name TotalTubePanelQty.
     * @return the TotalTubePanelQty
     */
    public Number getTotalTubePanelQty() {
        return (Number)getAttributeInternal(TOTALTUBEPANELQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalTubePanelQty.
     * @param value value to set the TotalTubePanelQty
     */
    public void setTotalTubePanelQty(Number value) {
        setAttributeInternal(TOTALTUBEPANELQTY, value);
    }

    /**
     * Gets the attribute value for RequisitionDate, using the alias name RequisitionDate.
     * @return the RequisitionDate
     */
    public Date getRequisitionDate() {
        return (Date)getAttributeInternal(REQUISITIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequisitionDate.
     * @param value value to set the RequisitionDate
     */
    public void setRequisitionDate(Date value) {
        setAttributeInternal(REQUISITIONDATE, value);
    }

    /**
     * Gets the attribute value for SpecialDetailing, using the alias name SpecialDetailing.
     * @return the SpecialDetailing
     */
    public String getSpecialDetailing() {
        return (String)getAttributeInternal(SPECIALDETAILING);
    }

    /**
     * Sets <code>value</code> as the attribute value for SpecialDetailing.
     * @param value value to set the SpecialDetailing
     */
    public void setSpecialDetailing(String value) {
        setAttributeInternal(SPECIALDETAILING, value);
    }

    /**
     * Gets the attribute value for YdsStatus, using the alias name YdsStatus.
     * @return the YdsStatus
     */
    public String getYdsStatus() {
        return (String)getAttributeInternal(YDSSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for YdsStatus.
     * @param value value to set the YdsStatus
     */
    public void setYdsStatus(String value) {
        setAttributeInternal(YDSSTATUS, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for Department, using the alias name Department.
     * @return the Department
     */
    public String getDepartment() {
        return (String)getAttributeInternal(DEPARTMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Department.
     * @param value value to set the Department
     */
    public void setDepartment(String value) {
        setAttributeInternal(DEPARTMENT, value);
    }

    /**
     * Gets the attribute value for DesignSheet, using the alias name DesignSheet.
     * @return the DesignSheet
     */
    public String getDesignSheet() {
        return (String)getAttributeInternal(DESIGNSHEET);
    }

    /**
     * Sets <code>value</code> as the attribute value for DesignSheet.
     * @param value value to set the DesignSheet
     */
    public void setDesignSheet(String value) {
        setAttributeInternal(DESIGNSHEET, value);
    }

    /**
     * Gets the attribute value for WashInstruction, using the alias name WashInstruction.
     * @return the WashInstruction
     */
    public String getWashInstruction() {
        return (String)getAttributeInternal(WASHINSTRUCTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashInstruction.
     * @param value value to set the WashInstruction
     */
    public void setWashInstruction(String value) {
        setAttributeInternal(WASHINSTRUCTION, value);
    }

    /**
     * Gets the attribute value for StyleDescription, using the alias name StyleDescription.
     * @return the StyleDescription
     */
    public String getStyleDescription() {
        return (String)getAttributeInternal(STYLEDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for StyleDescription.
     * @param value value to set the StyleDescription
     */
    public void setStyleDescription(String value) {
        setAttributeInternal(STYLEDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for SampleQtyDetails, using the alias name SampleQtyDetails.
     * @return the SampleQtyDetails
     */
    public String getSampleQtyDetails() {
        return (String)getAttributeInternal(SAMPLEQTYDETAILS);
    }

    /**
     * Sets <code>value</code> as the attribute value for SampleQtyDetails.
     * @param value value to set the SampleQtyDetails
     */
    public void setSampleQtyDetails(String value) {
        setAttributeInternal(SAMPLEQTYDETAILS, value);
    }

    /**
     * Gets the attribute value for Buyer, using the alias name Buyer.
     * @return the Buyer
     */
    public String getBuyer() {
        return (String)getAttributeInternal(BUYER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Buyer.
     * @param value value to set the Buyer
     */
    public void setBuyer(String value) {
        setAttributeInternal(BUYER, value);
    }

    /**
     * Gets the attribute value for Composition, using the alias name Composition.
     * @return the Composition
     */
    public String getComposition() {
        return (String)getAttributeInternal(COMPOSITION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Composition.
     * @param value value to set the Composition
     */
    public void setComposition(String value) {
        setAttributeInternal(COMPOSITION, value);
    }

    /**
     * Gets the attribute value for CutableWidth, using the alias name CutableWidth.
     * @return the CutableWidth
     */
    public String getCutableWidth() {
        return (String)getAttributeInternal(CUTABLEWIDTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutableWidth.
     * @param value value to set the CutableWidth
     */
    public void setCutableWidth(String value) {
        setAttributeInternal(CUTABLEWIDTH, value);
    }

    /**
     * Gets the attribute value for FabricRequestDate, using the alias name FabricRequestDate.
     * @return the FabricRequestDate
     */
    public Date getFabricRequestDate() {
        return (Date)getAttributeInternal(FABRICREQUESTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FabricRequestDate.
     * @param value value to set the FabricRequestDate
     */
    public void setFabricRequestDate(Date value) {
        setAttributeInternal(FABRICREQUESTDATE, value);
    }

    /**
     * Gets the attribute value for InventoryItemId, using the alias name InventoryItemId.
     * @return the InventoryItemId
     */
    public String getInventoryItemId() {
        return (String)getAttributeInternal(INVENTORYITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InventoryItemId.
     * @param value value to set the InventoryItemId
     */
    public void setInventoryItemId(String value) {
        setAttributeInternal(INVENTORYITEMID, value);
    }

    /**
     * Gets the attribute value for SourceSupplier, using the alias name SourceSupplier.
     * @return the SourceSupplier
     */
    public String getSourceSupplier() {
        return (String)getAttributeInternal(SOURCESUPPLIER);
    }

    /**
     * Sets <code>value</code> as the attribute value for SourceSupplier.
     * @param value value to set the SourceSupplier
     */
    public void setSourceSupplier(String value) {
        setAttributeInternal(SOURCESUPPLIER, value);
    }

    /**
     * Gets the attribute value for WashReceivedDate, using the alias name WashReceivedDate.
     * @return the WashReceivedDate
     */
    public Date getWashReceivedDate() {
        return (Date)getAttributeInternal(WASHRECEIVEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashReceivedDate.
     * @param value value to set the WashReceivedDate
     */
    public void setWashReceivedDate(Date value) {
        setAttributeInternal(WASHRECEIVEDDATE, value);
    }

    /**
     * Gets the attribute value for SampleDocNo, using the alias name SampleDocNo.
     * @return the SampleDocNo
     */
    public Number getSampleDocNo() {
        return (Number)getAttributeInternal(SAMPLEDOCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SampleDocNo.
     * @param value value to set the SampleDocNo
     */
    public void setSampleDocNo(Number value) {
        setAttributeInternal(SAMPLEDOCNO, value);
    }

    /**
     * Gets the attribute value for SampleDeadlineDate, using the alias name SampleDeadlineDate.
     * @return the SampleDeadlineDate
     */
    public Date getSampleDeadlineDate() {
        return (Date)getAttributeInternal(SAMPLEDEADLINEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SampleDeadlineDate.
     * @param value value to set the SampleDeadlineDate
     */
    public void setSampleDeadlineDate(Date value) {
        setAttributeInternal(SAMPLEDEADLINEDATE, value);
    }

    /**
     * Gets the attribute value for InsideWb, using the alias name InsideWb.
     * @return the InsideWb
     */
    public String getInsideWb() {
        return (String)getAttributeInternal(INSIDEWB);
    }

    /**
     * Sets <code>value</code> as the attribute value for InsideWb.
     * @param value value to set the InsideWb
     */
    public void setInsideWb(String value) {
        setAttributeInternal(INSIDEWB, value);
    }

    /**
     * Gets the attribute value for PocketingLeft, using the alias name PocketingLeft.
     * @return the PocketingLeft
     */
    public String getPocketingLeft() {
        return (String)getAttributeInternal(POCKETINGLEFT);
    }

    /**
     * Sets <code>value</code> as the attribute value for PocketingLeft.
     * @param value value to set the PocketingLeft
     */
    public void setPocketingLeft(String value) {
        setAttributeInternal(POCKETINGLEFT, value);
    }

    /**
     * Gets the attribute value for PocketingRight, using the alias name PocketingRight.
     * @return the PocketingRight
     */
    public String getPocketingRight() {
        return (String)getAttributeInternal(POCKETINGRIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for PocketingRight.
     * @param value value to set the PocketingRight
     */
    public void setPocketingRight(String value) {
        setAttributeInternal(POCKETINGRIGHT, value);
    }

    /**
     * Gets the attribute value for WashingUnit, using the alias name WashingUnit.
     * @return the WashingUnit
     */
    public String getWashingUnit() {
        return (String)getAttributeInternal(WASHINGUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashingUnit.
     * @param value value to set the WashingUnit
     */
    public void setWashingUnit(String value) {
        setAttributeInternal(WASHINGUNIT, value);
    }

    /**
     * Gets the attribute value for Serial, using the alias name Serial.
     * @return the Serial
     */
    public Number getSerial() {
        return (Number)getAttributeInternal(SERIAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Serial.
     * @param value value to set the Serial
     */
    public void setSerial(Number value) {
        setAttributeInternal(SERIAL, value);
    }

    /**
     * Gets the attribute value for SpecificationPattern, using the alias name SpecificationPattern.
     * @return the SpecificationPattern
     */
    public String getSpecificationPattern() {
        return (String)getAttributeInternal(SPECIFICATIONPATTERN);
    }

    /**
     * Sets <code>value</code> as the attribute value for SpecificationPattern.
     * @param value value to set the SpecificationPattern
     */
    public void setSpecificationPattern(String value) {
        setAttributeInternal(SPECIFICATIONPATTERN, value);
    }

    /**
     * Gets the attribute value for Zipper, using the alias name Zipper.
     * @return the Zipper
     */
    public String getZipper() {
        return (String)getAttributeInternal(ZIPPER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Zipper.
     * @param value value to set the Zipper
     */
    public void setZipper(String value) {
        setAttributeInternal(ZIPPER, value);
    }

    /**
     * Gets the attribute value for MockupQty, using the alias name MockupQty.
     * @return the MockupQty
     */
    public Number getMockupQty() {
        return (Number)getAttributeInternal(MOCKUPQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for MockupQty.
     * @param value value to set the MockupQty
     */
    public void setMockupQty(Number value) {
        setAttributeInternal(MOCKUPQTY, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjOntSampleStatusDetailEO() {
        return (RowIterator)getAttributeInternal(MNJONTSAMPLESTATUSDETAILEO);
    }

    /**
     * @return the associated entity MnjOntSampleStatusEOImpl.
     */
    public MnjOntSampleStatusEOImpl getMnjOntSampleStatusEO() {
        return (MnjOntSampleStatusEOImpl)getAttributeInternal(MNJONTSAMPLESTATUSEO);
    }

    /**
     * Sets <code>value</code> as the associated entity MnjOntSampleStatusEOImpl.
     */
    public void setMnjOntSampleStatusEO(MnjOntSampleStatusEOImpl value) {
        setAttributeInternal(MNJONTSAMPLESTATUSEO, value);
    }


    //    /**
//     * @return the associated entity MnjOntSampleStatusEOImpl.
//     */
//    public MnjOntSampleStatusEOImpl getMnjOntSampleStatusEO1() {
//        return (MnjOntSampleStatusEOImpl)getAttributeInternal(MNJONTSAMPLESTATUSEO1);
//    }
//
//    /**
//     * Sets <code>value</code> as the associated entity MnjOntSampleStatusEOImpl.
//     */
//    public void setMnjOntSampleStatusEO1(MnjOntSampleStatusEOImpl value) {
//        setAttributeInternal(MNJONTSAMPLESTATUSEO1, value);
//    }


    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getMnjOntSampleStatusViewOnlyEO() {
        return (EntityImpl)getAttributeInternal(MNJONTSAMPLESTATUSVIEWONLYEO);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setMnjOntSampleStatusViewOnlyEO(EntityImpl value) {
        setAttributeInternal(MNJONTSAMPLESTATUSVIEWONLYEO, value);
    }


    /**
     * @param lineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number lineId) {
        return new Key(new Object[]{lineId});
    }

    public ApplicationModule getAppM(){
        DCBindingContainer bindingContainer =
            (DCBindingContainer)BindingContext.getCurrent().getCurrentBindingsEntry();
        //BindingContext bindingContext = BindingContext.getCurrent();
        DCDataControl dc =
            bindingContainer.findDataControl("AppModuleDataControl"); // Name of application module in datacontrolBinding.cpx
        AppModuleImpl appM = (AppModuleImpl)dc.getDataProvider();
        return appM;
    }
    
    AppModuleImpl am = (AppModuleImpl)this.getAppM();

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        /* Sequence Generation Code of Header by PwC */  
         oracle.jbo.server.SequenceImpl s = new oracle.jbo.server.SequenceImpl("MNJ_ONT_SAMPLE_STATUS_LINE_S",getDBTransaction());          
         oracle.jbo.domain.Number sVal = s.getSequenceNumber();          
         setLineId(sVal);
         System.out.println("In Line Recently Created Line ID --> " + sVal);
         
        }
         
         /* End Sequence Generation Code of Header by PwC */
    

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
     protected void doDML(int operation, TransactionEvent e) {
             Map sessionScope = ADFContext.getCurrent().getSessionScope();   
             String user = (String)sessionScope.get("userId");
             
             //String user = "6489";
//             String orgId  =(String)sessionScope.get("orgId");
//             String unitName  =(String)sessionScope.get("unitName");
             
             System.out.println("ASSES INS DO DML 1 ------------------>"+user);
//             System.out.println("ASSES INS DO DML 2------------------>"+orgId);
//             System.out.println("ASSES INS DML 3 ------------------>"+unitName);
             
             if(DML_UPDATE == operation){
                       try {
                           
                           setLastUpdateDate((Date)Date.getCurrentDate());
                           System.out.println("ASSES DML_UPDATE ------------------>"+user);
                           setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                       } catch (SQLException f) {
                           System.out.println(f.getMessage());
                       }
                   }
                   else if (DML_INSERT == operation){
                    
                       try {
                           
                           //setHeaderNo(getSrNoString());
                           //setOrgId(new oracle.jbo.domain.Number(orgId));
                           //setAttribute1(unitName);
                           setCreationDate((Date)Date.getCurrentDate());
                           System.out.println("ASSES DML_INSERT ------------------>"+user);
                           setCreatedBy(new oracle.jbo.domain.Number(user));
                          
                          
                          
                       } catch (SQLException f) {
                           System.out.println(f.getMessage());
                       }
                   } 
             
             super.doDML(operation, e);
         }
}
