package model.entity;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jul 08 11:17:56 BDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjOntSampleStatusDetailEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        /* Sequence Generation Code of Header by PwC */  
         oracle.jbo.server.SequenceImpl s = new oracle.jbo.server.SequenceImpl("MNJ_ONT_SAMPLE_STATUS_DETAIL_S",getDBTransaction());          
         oracle.jbo.domain.Number sVal = s.getSequenceNumber();          
         setDetailId(sVal);
         System.out.println("In Detail Recently Created Detail ID --> " + sVal);
         /* End Sequence Generation Code of Header by PwC */
        
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
     protected void doDML(int operation, TransactionEvent e) {
             Map sessionScope = ADFContext.getCurrent().getSessionScope();   
             String user = (String)sessionScope.get("userId");
             String orgId  =(String)sessionScope.get("orgId");
             String unitName  =(String)sessionScope.get("unitName");
             
             System.out.println("ASSES INS DO DML 1 ------------------>"+user);
             System.out.println("ASSES INS DO DML 2------------------>"+orgId);
             System.out.println("ASSES INS DML 3 ------------------>"+unitName);
             
             if(DML_UPDATE == operation){
                       try {
                           
                           setLastUpdateDate((Date)Date.getCurrentDate()); 
                           setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                       } catch (SQLException f) {
                           System.out.println(f.getMessage());
                       }
                   }
                   else if (DML_INSERT == operation){
                    
                       try {
                           
                           //setHeaderNo(getSrNoString());
                           //setOrgId(new oracle.jbo.domain.Number(orgId));
                           //setAttribute1(unitName);
                           setCreationDate((Date)Date.getCurrentDate());  
                           setCreatedBy(new oracle.jbo.domain.Number(user));
                          
                          
                          
                       } catch (SQLException f) {
                           System.out.println(f.getMessage());
                       }
                   } 
             
             super.doDML(operation, e);
         }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        HederId {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getHederId();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setHederId((Number)value);
            }
        }
        ,
        LineId {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getLineId();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        DetailId {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getDetailId();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setDetailId((Number)value);
            }
        }
        ,
        Wash {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getWash();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setWash((String)value);
            }
        }
        ,
        SizeDet {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getSizeDet();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setSizeDet((String)value);
            }
        }
        ,
        Qty {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getQty();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setQty((String)value);
            }
        }
        ,
        ShrinkageSendToWash {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getShrinkageSendToWash();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setShrinkageSendToWash((Date)value);
            }
        }
        ,
        ShrinkageRcvdFromWash {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getShrinkageRcvdFromWash();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setShrinkageRcvdFromWash((Date)value);
            }
        }
        ,
        FinalSampleSentToWash {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getFinalSampleSentToWash();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setFinalSampleSentToWash((Date)value);
            }
        }
        ,
        FinalSampleRcvdDate {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getFinalSampleRcvdDate();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setFinalSampleRcvdDate((Date)value);
            }
        }
        ,
        SubmittedToMerchandiser {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getSubmittedToMerchandiser();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setSubmittedToMerchandiser((Date)value);
            }
        }
        ,
        Remarks {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getRemarks();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        WashProcess {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getWashProcess();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setWashProcess((String)value);
            }
        }
        ,
        ChamicalCost {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getChamicalCost();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setChamicalCost((String)value);
            }
        }
        ,
        EimScore {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getEimScore();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setEimScore((String)value);
            }
        }
        ,
        SendingItem {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getSendingItem();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setSendingItem((String)value);
            }
        }
        ,
        SendingQty {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getSendingQty();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setSendingQty((String)value);
            }
        }
        ,
        ChallanNo {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getChallanNo();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setChallanNo((String)value);
            }
        }
        ,
        WashRecQty {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getWashRecQty();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setWashRecQty((String)value);
            }
        }
        ,
        WashChallanNo {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getWashChallanNo();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setWashChallanNo((String)value);
            }
        }
        ,
        WashSendingQty {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getWashSendingQty();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setWashSendingQty((String)value);
            }
        }
        ,
        WashShortSentqty {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getWashShortSentqty();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setWashShortSentqty((String)value);
            }
        }
        ,
        WashReasonShortSending {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getWashReasonShortSending();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setWashReasonShortSending((String)value);
            }
        }
        ,
        WashRemarks {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getWashRemarks();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setWashRemarks((String)value);
            }
        }
        ,
        WetProcess {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getWetProcess();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setWetProcess((String)value);
            }
        }
        ,
        DryProcess {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getDryProcess();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setDryProcess((String)value);
            }
        }
        ,
        WashingUnit {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getWashingUnit();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setWashingUnit((String)value);
            }
        }
        ,
        HalfLegQty {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getHalfLegQty();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setHalfLegQty((String)value);
            }
        }
        ,
        TubePanelQty {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getTubePanelQty();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setTubePanelQty((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        HeaderId {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getHeaderId();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        ReceivedRemarks {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getReceivedRemarks();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setReceivedRemarks((String)value);
            }
        }
        ,
        ReceiveHalfLegQty {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getReceiveHalfLegQty();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setReceiveHalfLegQty((String)value);
            }
        }
        ,
        ReceiveQty {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getReceiveQty();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setReceiveQty((String)value);
            }
        }
        ,
        ReceiveTubeQty {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getReceiveTubeQty();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setReceiveTubeQty((String)value);
            }
        }
        ,
        SampleType {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getSampleType();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setSampleType((String)value);
            }
        }
        ,
        SendingRemarks {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getSendingRemarks();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setSendingRemarks((String)value);
            }
        }
        ,
        SendingToSampleDate {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getSendingToSampleDate();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setSendingToSampleDate((Date)value);
            }
        }
        ,
        SendingToSampleHalfLegQty {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getSendingToSampleHalfLegQty();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setSendingToSampleHalfLegQty((String)value);
            }
        }
        ,
        SendingToSampleQty {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getSendingToSampleQty();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setSendingToSampleQty((String)value);
            }
        }
        ,
        SendingToSampleRemarks {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getSendingToSampleRemarks();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setSendingToSampleRemarks((String)value);
            }
        }
        ,
        SendingToSampleTubeQty {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getSendingToSampleTubeQty();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setSendingToSampleTubeQty((String)value);
            }
        }
        ,
        StyleNumber {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getStyleNumber();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setStyleNumber((String)value);
            }
        }
        ,
        RcvSendToSampDate {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getRcvSendToSampDate();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setRcvSendToSampDate((Date)value);
            }
        }
        ,
        RcvSendToSampHalfLegQty {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getRcvSendToSampHalfLegQty();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setRcvSendToSampHalfLegQty((String)value);
            }
        }
        ,
        RcvSendToSampQty {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getRcvSendToSampQty();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setRcvSendToSampQty((String)value);
            }
        }
        ,
        RcvSendToSampRemarks {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getRcvSendToSampRemarks();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setRcvSendToSampRemarks((String)value);
            }
        }
        ,
        RcvSendToSampTubeQty {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getRcvSendToSampTubeQty();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setRcvSendToSampTubeQty((String)value);
            }
        }
        ,
        SampleDocNo {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getSampleDocNo();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setSampleDocNo((Number)value);
            }
        }
        ,
        SendingToSampleChallanNo {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getSendingToSampleChallanNo();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setSendingToSampleChallanNo((String)value);
            }
        }
        ,
        MnjOntSampleStatusLineEO {
            public Object get(MnjOntSampleStatusDetailEOImpl obj) {
                return obj.getMnjOntSampleStatusLineEO();
            }

            public void put(MnjOntSampleStatusDetailEOImpl obj, Object value) {
                obj.setMnjOntSampleStatusLineEO((MnjOntSampleStatusLineEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjOntSampleStatusDetailEOImpl object);

        public abstract void put(MnjOntSampleStatusDetailEOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HEDERID = AttributesEnum.HederId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int DETAILID = AttributesEnum.DetailId.index();
    public static final int WASH = AttributesEnum.Wash.index();
    public static final int SIZEDET = AttributesEnum.SizeDet.index();
    public static final int QTY = AttributesEnum.Qty.index();
    public static final int SHRINKAGESENDTOWASH = AttributesEnum.ShrinkageSendToWash.index();
    public static final int SHRINKAGERCVDFROMWASH = AttributesEnum.ShrinkageRcvdFromWash.index();
    public static final int FINALSAMPLESENTTOWASH = AttributesEnum.FinalSampleSentToWash.index();
    public static final int FINALSAMPLERCVDDATE = AttributesEnum.FinalSampleRcvdDate.index();
    public static final int SUBMITTEDTOMERCHANDISER = AttributesEnum.SubmittedToMerchandiser.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int WASHPROCESS = AttributesEnum.WashProcess.index();
    public static final int CHAMICALCOST = AttributesEnum.ChamicalCost.index();
    public static final int EIMSCORE = AttributesEnum.EimScore.index();
    public static final int SENDINGITEM = AttributesEnum.SendingItem.index();
    public static final int SENDINGQTY = AttributesEnum.SendingQty.index();
    public static final int CHALLANNO = AttributesEnum.ChallanNo.index();
    public static final int WASHRECQTY = AttributesEnum.WashRecQty.index();
    public static final int WASHCHALLANNO = AttributesEnum.WashChallanNo.index();
    public static final int WASHSENDINGQTY = AttributesEnum.WashSendingQty.index();
    public static final int WASHSHORTSENTQTY = AttributesEnum.WashShortSentqty.index();
    public static final int WASHREASONSHORTSENDING = AttributesEnum.WashReasonShortSending.index();
    public static final int WASHREMARKS = AttributesEnum.WashRemarks.index();
    public static final int WETPROCESS = AttributesEnum.WetProcess.index();
    public static final int DRYPROCESS = AttributesEnum.DryProcess.index();
    public static final int WASHINGUNIT = AttributesEnum.WashingUnit.index();
    public static final int HALFLEGQTY = AttributesEnum.HalfLegQty.index();
    public static final int TUBEPANELQTY = AttributesEnum.TubePanelQty.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int RECEIVEDREMARKS = AttributesEnum.ReceivedRemarks.index();
    public static final int RECEIVEHALFLEGQTY = AttributesEnum.ReceiveHalfLegQty.index();
    public static final int RECEIVEQTY = AttributesEnum.ReceiveQty.index();
    public static final int RECEIVETUBEQTY = AttributesEnum.ReceiveTubeQty.index();
    public static final int SAMPLETYPE = AttributesEnum.SampleType.index();
    public static final int SENDINGREMARKS = AttributesEnum.SendingRemarks.index();
    public static final int SENDINGTOSAMPLEDATE = AttributesEnum.SendingToSampleDate.index();
    public static final int SENDINGTOSAMPLEHALFLEGQTY = AttributesEnum.SendingToSampleHalfLegQty.index();
    public static final int SENDINGTOSAMPLEQTY = AttributesEnum.SendingToSampleQty.index();
    public static final int SENDINGTOSAMPLEREMARKS = AttributesEnum.SendingToSampleRemarks.index();
    public static final int SENDINGTOSAMPLETUBEQTY = AttributesEnum.SendingToSampleTubeQty.index();
    public static final int STYLENUMBER = AttributesEnum.StyleNumber.index();
    public static final int RCVSENDTOSAMPDATE = AttributesEnum.RcvSendToSampDate.index();
    public static final int RCVSENDTOSAMPHALFLEGQTY = AttributesEnum.RcvSendToSampHalfLegQty.index();
    public static final int RCVSENDTOSAMPQTY = AttributesEnum.RcvSendToSampQty.index();
    public static final int RCVSENDTOSAMPREMARKS = AttributesEnum.RcvSendToSampRemarks.index();
    public static final int RCVSENDTOSAMPTUBEQTY = AttributesEnum.RcvSendToSampTubeQty.index();
    public static final int SAMPLEDOCNO = AttributesEnum.SampleDocNo.index();
    public static final int SENDINGTOSAMPLECHALLANNO = AttributesEnum.SendingToSampleChallanNo.index();
    public static final int MNJONTSAMPLESTATUSLINEEO = AttributesEnum.MnjOntSampleStatusLineEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjOntSampleStatusDetailEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.entity.MnjOntSampleStatusDetailEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for HederId, using the alias name HederId.
     * @return the HederId
     */
    public Number getHederId() {
        return (Number)getAttributeInternal(HEDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HederId.
     * @param value value to set the HederId
     */
    public void setHederId(Number value) {
        setAttributeInternal(HEDERID, value);
    }

    /**
     * Gets the attribute value for LineId, using the alias name LineId.
     * @return the LineId
     */
    public Number getLineId() {
        return (Number)getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineId.
     * @param value value to set the LineId
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for DetailId, using the alias name DetailId.
     * @return the DetailId
     */
    public Number getDetailId() {
        return (Number)getAttributeInternal(DETAILID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DetailId.
     * @param value value to set the DetailId
     */
    public void setDetailId(Number value) {
        setAttributeInternal(DETAILID, value);
    }

    /**
     * Gets the attribute value for Wash, using the alias name Wash.
     * @return the Wash
     */
    public String getWash() {
        return (String)getAttributeInternal(WASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Wash.
     * @param value value to set the Wash
     */
    public void setWash(String value) {
        setAttributeInternal(WASH, value);
    }

    /**
     * Gets the attribute value for SizeDet, using the alias name SizeDet.
     * @return the SizeDet
     */
    public String getSizeDet() {
        return (String)getAttributeInternal(SIZEDET);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeDet.
     * @param value value to set the SizeDet
     */
    public void setSizeDet(String value) {
        setAttributeInternal(SIZEDET, value);
    }

    /**
     * Gets the attribute value for Qty, using the alias name Qty.
     * @return the Qty
     */
    public String getQty() {
        return (String)getAttributeInternal(QTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Qty.
     * @param value value to set the Qty
     */
    public void setQty(String value) {
        setAttributeInternal(QTY, value);
    }

    /**
     * Gets the attribute value for ShrinkageSendToWash, using the alias name ShrinkageSendToWash.
     * @return the ShrinkageSendToWash
     */
    public Date getShrinkageSendToWash() {
        return (Date)getAttributeInternal(SHRINKAGESENDTOWASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShrinkageSendToWash.
     * @param value value to set the ShrinkageSendToWash
     */
    public void setShrinkageSendToWash(Date value) {
        setAttributeInternal(SHRINKAGESENDTOWASH, value);
    }

    /**
     * Gets the attribute value for ShrinkageRcvdFromWash, using the alias name ShrinkageRcvdFromWash.
     * @return the ShrinkageRcvdFromWash
     */
    public Date getShrinkageRcvdFromWash() {
        return (Date)getAttributeInternal(SHRINKAGERCVDFROMWASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShrinkageRcvdFromWash.
     * @param value value to set the ShrinkageRcvdFromWash
     */
    public void setShrinkageRcvdFromWash(Date value) {
        setAttributeInternal(SHRINKAGERCVDFROMWASH, value);
    }

    /**
     * Gets the attribute value for FinalSampleSentToWash, using the alias name FinalSampleSentToWash.
     * @return the FinalSampleSentToWash
     */
    public Date getFinalSampleSentToWash() {
        return (Date)getAttributeInternal(FINALSAMPLESENTTOWASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for FinalSampleSentToWash.
     * @param value value to set the FinalSampleSentToWash
     */
    public void setFinalSampleSentToWash(Date value) {
        setAttributeInternal(FINALSAMPLESENTTOWASH, value);
    }

    /**
     * Gets the attribute value for FinalSampleRcvdDate, using the alias name FinalSampleRcvdDate.
     * @return the FinalSampleRcvdDate
     */
    public Date getFinalSampleRcvdDate() {
        return (Date)getAttributeInternal(FINALSAMPLERCVDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FinalSampleRcvdDate.
     * @param value value to set the FinalSampleRcvdDate
     */
    public void setFinalSampleRcvdDate(Date value) {
        setAttributeInternal(FINALSAMPLERCVDDATE, value);
    }

    /**
     * Gets the attribute value for SubmittedToMerchandiser, using the alias name SubmittedToMerchandiser.
     * @return the SubmittedToMerchandiser
     */
    public Date getSubmittedToMerchandiser() {
        return (Date)getAttributeInternal(SUBMITTEDTOMERCHANDISER);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubmittedToMerchandiser.
     * @param value value to set the SubmittedToMerchandiser
     */
    public void setSubmittedToMerchandiser(Date value) {
        setAttributeInternal(SUBMITTEDTOMERCHANDISER, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for WashProcess, using the alias name WashProcess.
     * @return the WashProcess
     */
    public String getWashProcess() {
        return (String)getAttributeInternal(WASHPROCESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashProcess.
     * @param value value to set the WashProcess
     */
    public void setWashProcess(String value) {
        setAttributeInternal(WASHPROCESS, value);
    }

    /**
     * Gets the attribute value for ChamicalCost, using the alias name ChamicalCost.
     * @return the ChamicalCost
     */
    public String getChamicalCost() {
        return (String)getAttributeInternal(CHAMICALCOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChamicalCost.
     * @param value value to set the ChamicalCost
     */
    public void setChamicalCost(String value) {
        setAttributeInternal(CHAMICALCOST, value);
    }

    /**
     * Gets the attribute value for EimScore, using the alias name EimScore.
     * @return the EimScore
     */
    public String getEimScore() {
        return (String)getAttributeInternal(EIMSCORE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EimScore.
     * @param value value to set the EimScore
     */
    public void setEimScore(String value) {
        setAttributeInternal(EIMSCORE, value);
    }

    /**
     * Gets the attribute value for SendingItem, using the alias name SendingItem.
     * @return the SendingItem
     */
    public String getSendingItem() {
        return (String)getAttributeInternal(SENDINGITEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for SendingItem.
     * @param value value to set the SendingItem
     */
    public void setSendingItem(String value) {
        setAttributeInternal(SENDINGITEM, value);
    }

    /**
     * Gets the attribute value for SendingQty, using the alias name SendingQty.
     * @return the SendingQty
     */
    public String getSendingQty() {
        return (String)getAttributeInternal(SENDINGQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SendingQty.
     * @param value value to set the SendingQty
     */
    public void setSendingQty(String value) {
        setAttributeInternal(SENDINGQTY, value);
    }

    /**
     * Gets the attribute value for ChallanNo, using the alias name ChallanNo.
     * @return the ChallanNo
     */
    public String getChallanNo() {
        return (String)getAttributeInternal(CHALLANNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChallanNo.
     * @param value value to set the ChallanNo
     */
    public void setChallanNo(String value) {
        setAttributeInternal(CHALLANNO, value);
    }

    /**
     * Gets the attribute value for WashRecQty, using the alias name WashRecQty.
     * @return the WashRecQty
     */
    public String getWashRecQty() {
        return (String)getAttributeInternal(WASHRECQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashRecQty.
     * @param value value to set the WashRecQty
     */
    public void setWashRecQty(String value) {
        setAttributeInternal(WASHRECQTY, value);
    }

    /**
     * Gets the attribute value for WashChallanNo, using the alias name WashChallanNo.
     * @return the WashChallanNo
     */
    public String getWashChallanNo() {
        return (String)getAttributeInternal(WASHCHALLANNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashChallanNo.
     * @param value value to set the WashChallanNo
     */
    public void setWashChallanNo(String value) {
        setAttributeInternal(WASHCHALLANNO, value);
    }

    /**
     * Gets the attribute value for WashSendingQty, using the alias name WashSendingQty.
     * @return the WashSendingQty
     */
    public String getWashSendingQty() {
        return (String)getAttributeInternal(WASHSENDINGQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashSendingQty.
     * @param value value to set the WashSendingQty
     */
    public void setWashSendingQty(String value) {
        setAttributeInternal(WASHSENDINGQTY, value);
    }

    /**
     * Gets the attribute value for WashShortSentqty, using the alias name WashShortSentqty.
     * @return the WashShortSentqty
     */
    public String getWashShortSentqty() {
        return (String)getAttributeInternal(WASHSHORTSENTQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashShortSentqty.
     * @param value value to set the WashShortSentqty
     */
    public void setWashShortSentqty(String value) {
        setAttributeInternal(WASHSHORTSENTQTY, value);
    }

    /**
     * Gets the attribute value for WashReasonShortSending, using the alias name WashReasonShortSending.
     * @return the WashReasonShortSending
     */
    public String getWashReasonShortSending() {
        return (String)getAttributeInternal(WASHREASONSHORTSENDING);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashReasonShortSending.
     * @param value value to set the WashReasonShortSending
     */
    public void setWashReasonShortSending(String value) {
        setAttributeInternal(WASHREASONSHORTSENDING, value);
    }

    /**
     * Gets the attribute value for WashRemarks, using the alias name WashRemarks.
     * @return the WashRemarks
     */
    public String getWashRemarks() {
        return (String)getAttributeInternal(WASHREMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashRemarks.
     * @param value value to set the WashRemarks
     */
    public void setWashRemarks(String value) {
        setAttributeInternal(WASHREMARKS, value);
    }

    /**
     * Gets the attribute value for WetProcess, using the alias name WetProcess.
     * @return the WetProcess
     */
    public String getWetProcess() {
        return (String)getAttributeInternal(WETPROCESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for WetProcess.
     * @param value value to set the WetProcess
     */
    public void setWetProcess(String value) {
        setAttributeInternal(WETPROCESS, value);
    }

    /**
     * Gets the attribute value for DryProcess, using the alias name DryProcess.
     * @return the DryProcess
     */
    public String getDryProcess() {
        return (String)getAttributeInternal(DRYPROCESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for DryProcess.
     * @param value value to set the DryProcess
     */
    public void setDryProcess(String value) {
        setAttributeInternal(DRYPROCESS, value);
    }

    /**
     * Gets the attribute value for WashingUnit, using the alias name WashingUnit.
     * @return the WashingUnit
     */
    public String getWashingUnit() {
        return (String)getAttributeInternal(WASHINGUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashingUnit.
     * @param value value to set the WashingUnit
     */
    public void setWashingUnit(String value) {
        setAttributeInternal(WASHINGUNIT, value);
    }

    /**
     * Gets the attribute value for HalfLegQty, using the alias name HalfLegQty.
     * @return the HalfLegQty
     */
    public String getHalfLegQty() {
        return (String)getAttributeInternal(HALFLEGQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for HalfLegQty.
     * @param value value to set the HalfLegQty
     */
    public void setHalfLegQty(String value) {
        setAttributeInternal(HALFLEGQTY, value);
    }

    /**
     * Gets the attribute value for TubePanelQty, using the alias name TubePanelQty.
     * @return the TubePanelQty
     */
    public String getTubePanelQty() {
        return (String)getAttributeInternal(TUBEPANELQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TubePanelQty.
     * @param value value to set the TubePanelQty
     */
    public void setTubePanelQty(String value) {
        setAttributeInternal(TUBEPANELQTY, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for ReceivedRemarks, using the alias name ReceivedRemarks.
     * @return the ReceivedRemarks
     */
    public String getReceivedRemarks() {
        return (String)getAttributeInternal(RECEIVEDREMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReceivedRemarks.
     * @param value value to set the ReceivedRemarks
     */
    public void setReceivedRemarks(String value) {
        setAttributeInternal(RECEIVEDREMARKS, value);
    }

    /**
     * Gets the attribute value for ReceiveHalfLegQty, using the alias name ReceiveHalfLegQty.
     * @return the ReceiveHalfLegQty
     */
    public String getReceiveHalfLegQty() {
        return (String)getAttributeInternal(RECEIVEHALFLEGQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReceiveHalfLegQty.
     * @param value value to set the ReceiveHalfLegQty
     */
    public void setReceiveHalfLegQty(String value) {
        setAttributeInternal(RECEIVEHALFLEGQTY, value);
    }

    /**
     * Gets the attribute value for ReceiveQty, using the alias name ReceiveQty.
     * @return the ReceiveQty
     */
    public String getReceiveQty() {
        return (String)getAttributeInternal(RECEIVEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReceiveQty.
     * @param value value to set the ReceiveQty
     */
    public void setReceiveQty(String value) {
        setAttributeInternal(RECEIVEQTY, value);
    }

    /**
     * Gets the attribute value for ReceiveTubeQty, using the alias name ReceiveTubeQty.
     * @return the ReceiveTubeQty
     */
    public String getReceiveTubeQty() {
        return (String)getAttributeInternal(RECEIVETUBEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReceiveTubeQty.
     * @param value value to set the ReceiveTubeQty
     */
    public void setReceiveTubeQty(String value) {
        setAttributeInternal(RECEIVETUBEQTY, value);
    }

    /**
     * Gets the attribute value for SampleType, using the alias name SampleType.
     * @return the SampleType
     */
    public String getSampleType() {
        return (String)getAttributeInternal(SAMPLETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SampleType.
     * @param value value to set the SampleType
     */
    public void setSampleType(String value) {
        setAttributeInternal(SAMPLETYPE, value);
    }

    /**
     * Gets the attribute value for SendingRemarks, using the alias name SendingRemarks.
     * @return the SendingRemarks
     */
    public String getSendingRemarks() {
        return (String)getAttributeInternal(SENDINGREMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for SendingRemarks.
     * @param value value to set the SendingRemarks
     */
    public void setSendingRemarks(String value) {
        setAttributeInternal(SENDINGREMARKS, value);
    }

    /**
     * Gets the attribute value for SendingToSampleDate, using the alias name SendingToSampleDate.
     * @return the SendingToSampleDate
     */
    public Date getSendingToSampleDate() {
        return (Date)getAttributeInternal(SENDINGTOSAMPLEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SendingToSampleDate.
     * @param value value to set the SendingToSampleDate
     */
    public void setSendingToSampleDate(Date value) {
        setAttributeInternal(SENDINGTOSAMPLEDATE, value);
    }

    /**
     * Gets the attribute value for SendingToSampleHalfLegQty, using the alias name SendingToSampleHalfLegQty.
     * @return the SendingToSampleHalfLegQty
     */
    public String getSendingToSampleHalfLegQty() {
        return (String)getAttributeInternal(SENDINGTOSAMPLEHALFLEGQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SendingToSampleHalfLegQty.
     * @param value value to set the SendingToSampleHalfLegQty
     */
    public void setSendingToSampleHalfLegQty(String value) {
        setAttributeInternal(SENDINGTOSAMPLEHALFLEGQTY, value);
    }

    /**
     * Gets the attribute value for SendingToSampleQty, using the alias name SendingToSampleQty.
     * @return the SendingToSampleQty
     */
    public String getSendingToSampleQty() {
        return (String)getAttributeInternal(SENDINGTOSAMPLEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SendingToSampleQty.
     * @param value value to set the SendingToSampleQty
     */
    public void setSendingToSampleQty(String value) {
        setAttributeInternal(SENDINGTOSAMPLEQTY, value);
    }

    /**
     * Gets the attribute value for SendingToSampleRemarks, using the alias name SendingToSampleRemarks.
     * @return the SendingToSampleRemarks
     */
    public String getSendingToSampleRemarks() {
        return (String)getAttributeInternal(SENDINGTOSAMPLEREMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for SendingToSampleRemarks.
     * @param value value to set the SendingToSampleRemarks
     */
    public void setSendingToSampleRemarks(String value) {
        setAttributeInternal(SENDINGTOSAMPLEREMARKS, value);
    }

    /**
     * Gets the attribute value for SendingToSampleTubeQty, using the alias name SendingToSampleTubeQty.
     * @return the SendingToSampleTubeQty
     */
    public String getSendingToSampleTubeQty() {
        return (String)getAttributeInternal(SENDINGTOSAMPLETUBEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SendingToSampleTubeQty.
     * @param value value to set the SendingToSampleTubeQty
     */
    public void setSendingToSampleTubeQty(String value) {
        setAttributeInternal(SENDINGTOSAMPLETUBEQTY, value);
    }

    /**
     * Gets the attribute value for StyleNumber, using the alias name StyleNumber.
     * @return the StyleNumber
     */
    public String getStyleNumber() {
        return (String)getAttributeInternal(STYLENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for StyleNumber.
     * @param value value to set the StyleNumber
     */
    public void setStyleNumber(String value) {
        setAttributeInternal(STYLENUMBER, value);
    }

    /**
     * Gets the attribute value for RcvSendToSampDate, using the alias name RcvSendToSampDate.
     * @return the RcvSendToSampDate
     */
    public Date getRcvSendToSampDate() {
        return (Date)getAttributeInternal(RCVSENDTOSAMPDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RcvSendToSampDate.
     * @param value value to set the RcvSendToSampDate
     */
    public void setRcvSendToSampDate(Date value) {
        setAttributeInternal(RCVSENDTOSAMPDATE, value);
    }

    /**
     * Gets the attribute value for RcvSendToSampHalfLegQty, using the alias name RcvSendToSampHalfLegQty.
     * @return the RcvSendToSampHalfLegQty
     */
    public String getRcvSendToSampHalfLegQty() {
        return (String)getAttributeInternal(RCVSENDTOSAMPHALFLEGQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for RcvSendToSampHalfLegQty.
     * @param value value to set the RcvSendToSampHalfLegQty
     */
    public void setRcvSendToSampHalfLegQty(String value) {
        setAttributeInternal(RCVSENDTOSAMPHALFLEGQTY, value);
    }

    /**
     * Gets the attribute value for RcvSendToSampQty, using the alias name RcvSendToSampQty.
     * @return the RcvSendToSampQty
     */
    public String getRcvSendToSampQty() {
        return (String)getAttributeInternal(RCVSENDTOSAMPQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for RcvSendToSampQty.
     * @param value value to set the RcvSendToSampQty
     */
    public void setRcvSendToSampQty(String value) {
        setAttributeInternal(RCVSENDTOSAMPQTY, value);
    }

    /**
     * Gets the attribute value for RcvSendToSampRemarks, using the alias name RcvSendToSampRemarks.
     * @return the RcvSendToSampRemarks
     */
    public String getRcvSendToSampRemarks() {
        return (String)getAttributeInternal(RCVSENDTOSAMPREMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for RcvSendToSampRemarks.
     * @param value value to set the RcvSendToSampRemarks
     */
    public void setRcvSendToSampRemarks(String value) {
        setAttributeInternal(RCVSENDTOSAMPREMARKS, value);
    }

    /**
     * Gets the attribute value for RcvSendToSampTubeQty, using the alias name RcvSendToSampTubeQty.
     * @return the RcvSendToSampTubeQty
     */
    public String getRcvSendToSampTubeQty() {
        return (String)getAttributeInternal(RCVSENDTOSAMPTUBEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for RcvSendToSampTubeQty.
     * @param value value to set the RcvSendToSampTubeQty
     */
    public void setRcvSendToSampTubeQty(String value) {
        setAttributeInternal(RCVSENDTOSAMPTUBEQTY, value);
    }

    /**
     * Gets the attribute value for SampleDocNo, using the alias name SampleDocNo.
     * @return the SampleDocNo
     */
    public Number getSampleDocNo() {
        return (Number)getAttributeInternal(SAMPLEDOCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SampleDocNo.
     * @param value value to set the SampleDocNo
     */
    public void setSampleDocNo(Number value) {
        setAttributeInternal(SAMPLEDOCNO, value);
    }

    /**
     * Gets the attribute value for SendingToSampleChallanNo, using the alias name SendingToSampleChallanNo.
     * @return the SendingToSampleChallanNo
     */
    public String getSendingToSampleChallanNo() {
        return (String)getAttributeInternal(SENDINGTOSAMPLECHALLANNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SendingToSampleChallanNo.
     * @param value value to set the SendingToSampleChallanNo
     */
    public void setSendingToSampleChallanNo(String value) {
        setAttributeInternal(SENDINGTOSAMPLECHALLANNO, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public MnjOntSampleStatusLineEOImpl getMnjOntSampleStatusLineEO() {
        return (MnjOntSampleStatusLineEOImpl)getAttributeInternal(MNJONTSAMPLESTATUSLINEEO);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setMnjOntSampleStatusLineEO(MnjOntSampleStatusLineEOImpl value) {
        setAttributeInternal(MNJONTSAMPLESTATUSLINEEO, value);
    }

    /**
     * @param detailId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number detailId) {
        return new Key(new Object[]{detailId});
    }


}
