package model.view;

import model.services.CustomViewImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 24 09:42:54 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjOntSampleStatusVOImpl extends CustomViewImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MnjOntSampleStatusVOImpl() {
    }

    /**
     * Returns the bind variable value for P_respId.
     * @return bind variable value for P_respId
     */
    public String getP_respId() {
        return (String)getNamedWhereClauseParam("P_respId");
    }

    /**
     * Sets <code>value</code> for bind variable P_respId.
     * @param value value to bind as P_respId
     */
    public void setP_respId(String value) {
        setNamedWhereClauseParam("P_respId", value);
    }

    /**
     * Returns the bind variable value for P_userId.
     * @return bind variable value for P_userId
     */
    public String getP_userId() {
        return (String)getNamedWhereClauseParam("P_userId");
    }

    /**
     * Sets <code>value</code> for bind variable P_userId.
     * @param value value to bind as P_userId
     */
    public void setP_userId(String value) {
        setNamedWhereClauseParam("P_userId", value);
    }
}
