package model.view;

import model.services.CustomViewImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 10 13:11:08 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjOntSampleStatusLineVOImpl extends CustomViewImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MnjOntSampleStatusLineVOImpl() {
    }
}
